# TO DO LIST

-Clean Data Columns for customer data

-Get list of unique customers

-Anonymise customers

-Drop unnecessary columns

-Make a new column containing XDC, Size, Coating seperated with "-"

-Get list of all the unique combinations XDC-Size-Coating

-Anonymise the names in this new column

-Check the delivery time

## Values to Anonymize¶
customer name --> new column ==> customer IDs

[XDC] PDC / PDC-C / NDC --> P1, P2, P3 | DONE

XDC --> new column ==> NOZ

[Size] 50 / 60 / 70 / 80 / 90 / 100 --> 00 / 10 / 20 / 30 / 40 / 50

[Size] CS / CM / CL --> C1 / C2 / C3

[Size] NL / NM / NH --> N1 / N2 / N3

[Size] N200 / N300 / N400 --> N4 / N5 / N6

[Size] sN100 / sN200 / sN300 / sN400 / sN500 --> N7 / N8 / N9 / N10 / N11

[Size] SolB / FAT / H2O / Dummy / Training  -->  X1 / X2 / X3 / X4 / X5

[Coating] T0 / T1 / T2 / T3 / T4 / T1sym --> B0 / B1 / B2 / B3 / B4 / B5

XDC --> new column ==> Modification

Machines!

In [1]:
import pandas as pd
import numpy as np

customer_df = pd.read_csv("/Users/esrabecker/Desktop/GitHub/DA_Midterm_Project/_Data/Customer_Data.csv", sep= ';')
pd.set_option('display.max_columns', None)
customer_df

,Customer,XDC,Size,Coating,Amount,Fitting,Date_Order,Date_Delivery_Ought,Date_Delivery_Is,Delivery_Comment,General_Comment,Division_Tag,Machine,Machine_Comment,Machine_Type,Training_Kits,Dummy_Sets,Channels,Delivery_Time,Locality_Country,Locality_City,Sci_Ltd,Sci_Inc,Contract_Manufacturing,Replacement_Delivery,Replacement_for_ID,PO,PO_Inc,OC_AG,OC_Inc,Date_Order_Month,Date_Delivery_Month,Date_Order_Year,Date_Delivery_Year,Finished
0,ADC,PDC,80,T2,18.0,S3,2018-11-30,2019-02-15,2021-03-05,Part 1,Teil 1 zusammen mit 12x OEM's + 24 Dummy Sets...,NaN,1.0,12.0,OEM,NaN,24,NaN,826.0,UK,Witney,NaN,NaN,NaN,NaN,NaN,0A84204,NaN,23602,NaN,2018-11,2021-03,2018.0,2021.0,1
1,ADC,PDC,80,T2,18.0,S3,2018-11-30,NaN,2021-03-15,Part 2,Teil 2 zusammen mit 12x OEM's + 24 Dummy Sets...,NaN,1.0,12.0,OEM,NaN,24,NaN,836.0,UK,Witney,NaN,NaN,NaN,NaN,NaN,0A84204,NaN,23602,NaN,2018-11,2021-03,2018.0,2021.0,1
2,Optolane Technologies Inc,PDC,90,T1,10.0,S5/S11,2019-03-19,NaN,2020-01-31,Dez.,zusammen mit S100-Rocket I Portal Upgrade (10...,NaN,1.0,NaN,S100,NaN,NaN,10,318.0,South Korea,Seongnam-si (Gyeonggi-do),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-03,2020-01,2019.0,2020.0,1
3,MDC BIMSB,PDC-C,CS,NaN,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,NaN,NaN,NaN,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1
4,MDC BIMSB,PDC-C,CM,NaN,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,NaN,NaN,NaN,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2782,ADC,PDC,80,T2,35.0,S3,2022-06-01,2022-06-01,NaN,NaN,June22 Call Off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ireland,Donegal,NaN,NaN,NaN,NaN,NaN,4700849191-1417-IED,NaN,26418,NaN,2022-06,NaN,2022.0,NaN,0
2783,Randox Teoranta,PDC,80,NaN,10.0,S5/S11,2022-07-13,2022-10-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ireland,Dungloe,NaN,NaN,NaN,NaN,NaN,526309,NaN,27331,NaN,2022-07,NaN,2022.0,NaN,0
2784,MPI KGF,PDC,80,NaN,3.0,S5/S11,2021-09-02,2022-11-25,NaN,NaN,NaN,Institut für Kolloid -und Grenzflaechenforschung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Germany,Potsdam-Golm,NaN,NaN,NaN,NaN,NaN,4715373/KOLL 130,NaN,27487,NaN,2021-09,NaN,2021.0,NaN,0
2785,Fred Hutchinson Cancer Center,PDC,80,T2,3.0,S5/S11,2022-09-02,NaN,NaN,NaN,NaN,NaN,1.0,S3,S3,NaN,NaN,2,NaN,USA,Seattle,NaN,NaN,NaN,NaN,NaN,0001121209,NaN,27488,100913.0,2022-09,NaN,2022.0,NaN,0
2786,Scienion Inc,PDC,80,T1,2.0,S5/S11,2022-09-02,NaN,NaN,NaN,NaN,NaN,1.0,S3,S3,NaN,NaN,2,NaN,USA,Tempe,NaN,NaN,NaN,NaN,NaN,10AUG2022 S3 preorder,NaN,27489,100914.0,2022-09,NaN,2022.0,NaN,0

In [2]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2787 entries, 0 to 2786
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer                2787 non-null   object
 1   XDC                     2787 non-null   object
 2   Size                    2787 non-null   object
 3   Coating                 1962 non-null   object
 4   Amount                  2787 non-null   float64
 5   Fitting                 2762 non-null   object
 6   Date_Order              2786 non-null   object
 7   Date_Delivery_Ought     1925 non-null   object
 8   Date_Delivery_Is        2627 non-null   object
 9   Delivery_Comment        818 non-null    object
 10  General_Comment         771 non-null    object
 11  Division_Tag            332 non-null    object
 12  Machine                 397 non-null    float64
 13  Machine_Comment         207 non-null    object
 14  Machine_Type            397 non-null    object
 15  Training_Kits           94 non-null     float64
 16  Dummy_Sets              156 non-null    object
 17  Channels                367 non-null    object
 18  Delivery_Time           2627 non-null   float64
 19  Locality_Country        2787 non-null   object
 20  Locality_City           2785 non-null   object
 21  Sci_Ltd                 0 non-null      float64
 22  Sci_Inc                 691 non-null    float64
 23  Contract_Manufacturing  42 non-null     float64
 24  Replacement_Delivery    475 non-null    float64
 25  Replacement_for_ID      467 non-null    object
 26  PO                      2587 non-null   object
 27  PO_Inc                  533 non-null    object
 28  OC_AG                   2571 non-null   object
 29  OC_Inc                  233 non-null    float64
 30  Date_Order_Month        2786 non-null   object
 31  Date_Delivery_Month     2627 non-null   object
 32  Date_Order_Year         2786 non-null   float64
 33  Date_Delivery_Year      2627 non-null   float64
 34  Finished                2787 non-null   int64
dtypes: float64(11), int64(1), object(23)
memory usage: 762.2+ KB

## Lowercase Column Names

To standirize the column names we convert all the letter to lowercase.

In [3]:
customer_lower = list(customer_df.columns.str.lower())
customer_lower

['customer',
 'xdc',
 'size',
 'coating',
 'amount',
 'fitting',
 'date_order',
 'date_delivery_ought',
 'date_delivery_is',
 'delivery_comment',
 'general_comment',
 'division_tag',
 'machine',
 'machine_comment',
 'machine_type',
 'training_kits',
 'dummy_sets',
 'channels',
 'delivery_time',
 'locality_country',
 'locality_city',
 'sci_ltd',
 'sci_inc',
 'contract_manufacturing',
 'replacement_delivery',
 'replacement_for_id',
 'po',
 'po_inc',
 'oc_ag',
 'oc_inc',
 'date_order_month',
 'date_delivery_month',
 'date_order_year',
 'date_delivery_year',
 'finished']

In [4]:
customer_df.columns = customer_lower

In [5]:
customer_df

,customer,xdc,size,coating,amount,fitting,date_order,date_delivery_ought,date_delivery_is,delivery_comment,general_comment,division_tag,machine,machine_comment,machine_type,training_kits,dummy_sets,channels,delivery_time,locality_country,locality_city,sci_ltd,sci_inc,contract_manufacturing,replacement_delivery,replacement_for_id,po,po_inc,oc_ag,oc_inc,date_order_month,date_delivery_month,date_order_year,date_delivery_year,finished
0,ADC,PDC,80,T2,18.0,S3,2018-11-30,2019-02-15,2021-03-05,Part 1,Teil 1 zusammen mit 12x OEM's + 24 Dummy Sets...,NaN,1.0,12.0,OEM,NaN,24,NaN,826.0,UK,Witney,NaN,NaN,NaN,NaN,NaN,0A84204,NaN,23602,NaN,2018-11,2021-03,2018.0,2021.0,1
1,ADC,PDC,80,T2,18.0,S3,2018-11-30,NaN,2021-03-15,Part 2,Teil 2 zusammen mit 12x OEM's + 24 Dummy Sets...,NaN,1.0,12.0,OEM,NaN,24,NaN,836.0,UK,Witney,NaN,NaN,NaN,NaN,NaN,0A84204,NaN,23602,NaN,2018-11,2021-03,2018.0,2021.0,1
2,Optolane Technologies Inc,PDC,90,T1,10.0,S5/S11,2019-03-19,NaN,2020-01-31,Dez.,zusammen mit S100-Rocket I Portal Upgrade (10...,NaN,1.0,NaN,S100,NaN,NaN,10,318.0,South Korea,Seongnam-si (Gyeonggi-do),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-03,2020-01,2019.0,2020.0,1
3,MDC BIMSB,PDC-C,CS,NaN,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,NaN,NaN,NaN,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1
4,MDC BIMSB,PDC-C,CM,NaN,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,NaN,NaN,NaN,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2782,ADC,PDC,80,T2,35.0,S3,2022-06-01,2022-06-01,NaN,NaN,June22 Call Off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ireland,Donegal,NaN,NaN,NaN,NaN,NaN,4700849191-1417-IED,NaN,26418,NaN,2022-06,NaN,2022.0,NaN,0
2783,Randox Teoranta,PDC,80,NaN,10.0,S5/S11,2022-07-13,2022-10-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ireland,Dungloe,NaN,NaN,NaN,NaN,NaN,526309,NaN,27331,NaN,2022-07,NaN,2022.0,NaN,0
2784,MPI KGF,PDC,80,NaN,3.0,S5/S11,2021-09-02,2022-11-25,NaN,NaN,NaN,Institut für Kolloid -und Grenzflaechenforschung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Germany,Potsdam-Golm,NaN,NaN,NaN,NaN,NaN,4715373/KOLL 130,NaN,27487,NaN,2021-09,NaN,2021.0,NaN,0
2785,Fred Hutchinson Cancer Center,PDC,80,T2,3.0,S5/S11,2022-09-02,NaN,NaN,NaN,NaN,NaN,1.0,S3,S3,NaN,NaN,2,NaN,USA,Seattle,NaN,NaN,NaN,NaN,NaN,0001121209,NaN,27488,100913.0,2022-09,NaN,2022.0,NaN,0
2786,Scienion Inc,PDC,80,T1,2.0,S5/S11,2022-09-02,NaN,NaN,NaN,NaN,NaN,1.0,S3,S3,NaN,NaN,2,NaN,USA,Tempe,NaN,NaN,NaN,NaN,NaN,10AUG2022 S3 preorder,NaN,27489,100914.0,2022-09,NaN,2022.0,NaN,0

## Get Unique Customer Names

We get the unique customer names for the unique customer ids. Later we'll create a dictionary which we'll use for our new column customer_id.

In [6]:
customer_df['customer'].value_counts()

ADC                                       409
Mobidiag Ltd (Hologic)                    122
Scienion Inc                              113
Cellenion SASU                             71
Randox Teoranta                            58
                                         ...
MBARI                                       1
Changzou Siyao Pharmaceuticals Co. Ltd      1
Paratus Diagnostics                         1
Greiner Bio-One GmbH                        1
Fred Hutchinson Cancer Center               1
Name: customer, Length: 318, dtype: int64

In [7]:
#Unique Customer Names
customer_list = customer_df['customer'].unique()
customer_list

array(['ADC', 'Optolane Technologies Inc', 'MDC BIMSB', 'Scienion Inc',
       'fzmb GmbH', 'Eindhoven University of Technology',
       'Changzou Siyao Pharmaceuticals Co. Ltd', 'MagArray Inc',
       'Fraunhofer IZI', 'Adarza BioSystems Inc', 'Cellenion SASU',
       'AstraZeneca UK Ltd', 'PSG Procurement Services GmbH',
       'Randox Teoranta', 'iLINE Microsystems S.L.', 'Minifab PTY Ltd',
       'Automobi Molecular Diagnostice Co. Ltd',
       'TestLine Clinical Diagnostics s.r.o.', 'IMTEK',
       'Phadia AB (Thermo Fisher Scientific)', 'Viramed Biotech AG',
       'MBio Diagnostics Inc', 'A*Star Research Entities',
       'SQI Diagnostics Systems Inc', 'Angle Biosiences Inc',
       'Verily Life Sciences', 'Safeguard Biosystems Manufacturing',
       'IMEC vzw', 'Vitro S.A.', 'Safeguard Biosystems Inc',
       'Invitae Corporation', 'Zymergen', 'Charite', 'INL', 'Bio Rad',
       'InSilixa Inc (Cepheid)', 'Inside Biometrics Int Ltd',
       'DTU Health Tech', 'LXRepair SAS', 'Pamgene International B.V.',
       'Institute Curie', 'Erasmus MC Rotterdam', 'AerNos Inc',
       'Qorvo Biotechnologies LLC', 'Gener8 Inc', 'Genomica S.A.U.',
       'Antech Diagnostics', 'Rice University', 'GenMark Diagnostics Inc',
       'Luminex Operation', 'UniSensor S.A.', 'UC Berkeley',
       'Mobidiag Ltd (Hologic)', 'Synthego', 'WAD GROUP CO. Ltd',
       'Duke University Healthsystems Inc', 'Earlham Institute', 'BCCRC',
       'RayBiotech Inc', 'Northeastern University',
       'Siemens Healthineers Nederland B.V.', 'PCL Inc',
       'The Francis Crick Institute', 'Quantum Design Japan Inc (QDJ)',
       'MPI KGF', 'ITE', 'IMP', 'Uni Portsmouth',
       'Universitaetsklinikum Jena', 'R-Biopharm AG',
       'Aryballe Technologies', 'Imperial College',
       'Janssen Pharmaceutica NV', 'McGill University',
       'Mint Diagnostics Ltd', 'Uni Wageningen', 'Boehringer Ingelheim',
       'GenID GmbH', 'Uni Houston', 'MIT', 'MSKCC', 'HOIL Biomed Inc',
       'DNAe Diagnostics Ltd', 'DKFZ', 'Greiner Bio-One GmbH',
       'Hochschule Furtwangen', 'LifeLineLab s.r.l.',
       'Infynity Biomarkers', 'Osler Diagnostics Ltd', 'FH Aachen',
       'Euroimmun AG', 'Genalyte Inc', 'Attomarker Ltd',
       'Zepto Life Technology', 'Enzyre B.V.', 'Uni Nottingham', 'UCSF',
       'Innobiochips', 'HeMemics Biotechnologies Inc',
       'NanoView Biosciences', 'Uni Edinburgh', 'ICFO',
       'Queen Mary University of London (QMUL)', 'Fraunhofer CMI',
       'Dr. Fooke - Achterrath Laboratorien GmbH',
       'Suzhou Epitope Biotechnolgoy Ltd', 'Dynamic Biosensors GmbH',
       'Immunovia AB', 'UMCG', 'Diarect AG', 'UAB Grida',
       'CTC Analytics AG', 'Chan Zuckerberg BioHub',
       'Pacific Northwest National Laboratory', 'Alkor Impex Ltd',
       'Uni Bundeswehr Muenchen', 'Uniklinik RWTH Aachen',
       'Aselsan Electronic Industries Inc', 'Surfix BV', 'IIBR',
       'Glycan Therapeutics LLC', 'Labskin Creations',
       'Future Diagnostics Solutions BV', 'Bio Palette Ltd', 'InDevR Inc',
       'Uni Turku', 'RosChemAnalitica LLC',
       'Zhongke Scientific & Technical Co. Ltd', 'WAMA Diagnostics SA',
       'Anyspectra Scientific Ltd', 'Flashdx Shenzhen Inc',
       'MiDIAGNOSTICS', 'CellenCHIP Projekt', 'BRAINBox Solutions Inc',
       'RIVM', 'Uni Wien', 'Uni Bodenkultur', 'University of Rochester',
       'Medical University of Vienna', 'NanoVation-GS Ltd',
       'LTS Lohmann Therapie-Systeme AG', 'Medtronic', 'CIC biomaGUNE',
       'sciCOVIR 19 Projekt', 'AXO Science', 'Technion Ltd', 'MPI BPC',
       'Vidya Holdings Ltd', 'Universidad Politechnica de Valencia',
       'ENS Paris Saclay', 'Uni Cambridge', 'Applied Microarrays Inc',
       'Uni Stanford', 'QuantiScienitific  Llc',
       'SLAC National Accelerator Laboratory', 'SiDx Inc', 'Semiotik Llc',
       'Dendris', 'UCL', 'CSIC', 'Bruker Optik GmbH', 'HelixBind Inc',
       'Torus Biosystems Inc', 'Roche Diagnostics GmbH', 'RCPE GmbH',
       'Universitätsmedizin Mannheim', 'EPFL', 'Caura.me Ltd',
       'GENSPEED Biotech GmbH', 'UMG Universitätsmedizin Göttingen',
       "Queen's University Belfast", 'Instituto de Salud Carlos III',
       'Nypro Limited / DnaNudge', 'Uni Georgia',
       'Zhuhai Sinochips Bioscience Co Ltd', 'MBARI', 'WWC',
       'Northwestern University', 'Central Scientific Commerce Inc',
       'Lumensia Sensors', 'McMaster Uni',
       'Siemens Healthcare Diagnostics', 'ZYMOPTIQ', 'Antelope DX',
       'Aries s.r.l.', 'Genome Sciences Centre', 'Kephera Diagnostics',
       'Universitätsklinikum Köln', 'NY Genome Center',
       'Joanneum Research Forschungsgesellschaft', 'Z Biotech', 'HES-SO',
       'Karlsruher Institut für Technologie (KIT)', 'NIH',
       'LEX Diagnostics Ltd', 'Scienion Ltd', 'Keren Instruments',
       'Ulster University', 'C&D Co', 'Utrecht University (UMC)',
       'Sanwa Biotech', 'European Commission (JRC)', 'D-Tek',
       'Scienion GmbH', 'BioTT', 'Cedars-Sinai', 'Zenostic', 'Cube Dx',
       'CellInk AB', 'Weizmann Institute of Science', 'AMC Amsterdam',
       'Immunodiagnostika', 'Velocity Sciences', 'Ecole Centrale de Lyon',
       'Proactive Diagnostics', 'BMS Cambridge', 'RayBiotech Life',
       'AMDI Lantana', 'Abcam Plc (UK)', 'Merck Sharp & Dohme Corp',
       'Abcam Plc (USA)', 'K&K Constultant Group Inc',
       'Cleverlab Co. Ltd', 'J-BIO', 'Microvisk Technologies Ltd',
       'Grace BioLabs', 'Hospital Ramon y Cajal', 'BYU-Provo', 'UCSD',
       'Lawrence Berkeley National Laboratory', 'Mammoth Biosciences Inc',
       'University Medical', 'Université de Rennes', 'Micronit B.V.',
       'Phillips-Medisize (Molex)', 'Eli Lilly and Company',
       'Universitätsklinikum Mainz',
       'Korean Institute of Science and Technology (KIST)',
       'Ortho Clinical Diagnostics', 'Eastern Virginia Medical School',
       'Universite Grenoble Alpes', 'Vanderbilt University',
       'SF Metsource Ltd', 'QuantuMDx Group Limited',
       'University of York', 'California Institute of Technology',
       'CEA Grenoble', 'BASF', 'VTT Technical Research Centre Finland',
       'Genentech Inc', 'Mecwins SA', 'MVZ',
       "Children's Cancer Institute", 'HZI',
       'BAM - Bundesanstalt für Materialforschung und prüfung',
       'Institute of Chemistry', 'Paratus Diagnostics',
       'Rutgers University', 'Shanghai Aifei Electronic Technology Co',
       'Syngenta Crop Protection AG',
       'Ben-Gurion University of the Negev', 'University of Copenhagen',
       'Palogen', 'Brigham Young University', 'CEA Saclay',
       'Molecular Assemblies lnc', 'CNIO',
       "Université Evry Val d'Essonne", 'EUROCLONE SpA',
       'Helios Bioelectronics', 'Fraunhofer USA', 'ICR', 'Quidel',
       'Uni Regenburg', 'ISAR Bioscience GmbH', 'Broad Institute',
       'Uni Queensland', 'Community College for Sioux Falls',
       'SG Medical', 'Fundación Tecnalia Research & Innovation',
       'New Business International Trading', 'Instituto SCITEC CNR',
       'TU Bergakademie Freiberg', 'TTP plc', 'Delrus', 'CSIC-INTA',
       'Biosero Inc',
       'LIST - Luxemburg Institute of Science and Technology',
       'University of Wisconsin', 'Bar-Ilan University',
       'Proteome Sciences R&D GmbH', 'CSIC-ICAQ', 'Quotient Suisse',
       'Uni Oxford', 'Johns Hopkins University', 'RemAb Therapeutics SL',
       'TU München', 'Nanosynex Ltd', 'Spectragenetics',
       'Aesku.Diagnostics GmbH', 'Altos Labs Inc',
       'Beth Israel Deaconess Medical Center', 'EWHA Womans University',
       'Accela', 'Xsensio SA', 'Institut Pasteur Paris',
       'Lund University', 'Nanyang Technological University',
       'AMDI Sunflower', 'Uni Zürich', 'Quotient',
       'University of Liverpool', 'Randox Crumlin',
       'Mayo Foundation - Mayo Clinic Receiving Hub', 'Robert Bosch GmbH',
       'AQUARRAY GmbH', 'Immundiagnostik AG',
       'Fred Hutchinson Cancer Center'], dtype=object)

### Create A Dictionary for Unique Customer Ids

In [8]:
#sorted the customer name to give them index customer id
customer_list_sorted = sorted(customer_list)
keys = customer_list_sorted

In [9]:
#customer id list for the values of dict
values =list(range(1,len(customer_list_sorted)+1))
values

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318]

We created the keys and values of our dictionary now with the function we'll assign them to each other.

In [10]:
# create dictionary with our customer name and id to assign them each other.
def create_dictionary(keys, values):
    result = {} # empty dictionary
    for key, value in zip(keys, values):
        result[key] = value
    return result
# use create_dictionary func.
print(create_dictionary(keys=keys, values=values))

create_dict= create_dictionary(keys=keys, values=values)

{'A*Star Research Entities': 1, 'ADC': 2, 'AMC Amsterdam': 3, 'AMDI Lantana': 4, 'AMDI Sunflower': 5, 'AQUARRAY GmbH': 6, 'AXO Science': 7, 'Abcam Plc (UK)': 8, 'Abcam Plc (USA)': 9, 'Accela': 10, 'Adarza BioSystems Inc': 11, 'AerNos Inc': 12, 'Aesku.Diagnostics GmbH': 13, 'Alkor Impex Ltd': 14, 'Altos Labs Inc': 15, 'Angle Biosiences Inc': 16, 'Antech Diagnostics': 17, 'Antelope DX': 18, 'Anyspectra Scientific Ltd': 19, 'Applied Microarrays Inc': 20, 'Aries s.r.l.': 21, 'Aryballe Technologies': 22, 'Aselsan Electronic Industries Inc': 23, 'AstraZeneca UK Ltd': 24, 'Attomarker Ltd': 25, 'Automobi Molecular Diagnostice Co. Ltd': 26, 'BAM - Bundesanstalt für Materialforschung und prüfung': 27, 'BASF': 28, 'BCCRC': 29, 'BMS Cambridge': 30, 'BRAINBox Solutions Inc': 31, 'BYU-Provo': 32, 'Bar-Ilan University': 33, 'Ben-Gurion University of the Negev': 34, 'Beth Israel Deaconess Medical Center': 35, 'Bio Palette Ltd': 36, 'Bio Rad': 37, 'BioTT': 38, 'Biosero Inc': 39, 'Boehringer Ingelheim': 40, 'Brigham Young University': 41, 'Broad Institute': 42, 'Bruker Optik GmbH': 43, 'C&D Co': 44, 'CEA Grenoble': 45, 'CEA Saclay': 46, 'CIC biomaGUNE': 47, 'CNIO': 48, 'CSIC': 49, 'CSIC-ICAQ': 50, 'CSIC-INTA': 51, 'CTC Analytics AG': 52, 'California Institute of Technology': 53, 'Caura.me Ltd': 54, 'Cedars-Sinai': 55, 'CellInk AB': 56, 'CellenCHIP Projekt': 57, 'Cellenion SASU': 58, 'Central Scientific Commerce Inc': 59, 'Chan Zuckerberg BioHub': 60, 'Changzou Siyao Pharmaceuticals Co. Ltd': 61, 'Charite': 62, "Children's Cancer Institute": 63, 'Cleverlab Co. Ltd': 64, 'Community College for Sioux Falls': 65, 'Cube Dx': 66, 'D-Tek': 67, 'DKFZ': 68, 'DNAe Diagnostics Ltd': 69, 'DTU Health Tech': 70, 'Delrus': 71, 'Dendris': 72, 'Diarect AG': 73, 'Dr. Fooke - Achterrath Laboratorien GmbH': 74, 'Duke University Healthsystems Inc': 75, 'Dynamic Biosensors GmbH': 76, 'ENS Paris Saclay': 77, 'EPFL': 78, 'EUROCLONE SpA': 79, 'EWHA Womans University': 80, 'Earlham Institute': 81, 'Eastern Virginia Medical School': 82, 'Ecole Centrale de Lyon': 83, 'Eindhoven University of Technology': 84, 'Eli Lilly and Company': 85, 'Enzyre B.V.': 86, 'Erasmus MC Rotterdam': 87, 'Euroimmun AG': 88, 'European Commission (JRC)': 89, 'FH Aachen': 90, 'Flashdx Shenzhen Inc': 91, 'Fraunhofer CMI': 92, 'Fraunhofer IZI': 93, 'Fraunhofer USA': 94, 'Fred Hutchinson Cancer Center': 95, 'Fundación Tecnalia Research & Innovation': 96, 'Future Diagnostics Solutions BV': 97, 'GENSPEED Biotech GmbH': 98, 'GenID GmbH': 99, 'GenMark Diagnostics Inc': 100, 'Genalyte Inc': 101, 'Genentech Inc': 102, 'Gener8 Inc': 103, 'Genome Sciences Centre': 104, 'Genomica S.A.U.': 105, 'Glycan Therapeutics LLC': 106, 'Grace BioLabs': 107, 'Greiner Bio-One GmbH': 108, 'HES-SO': 109, 'HOIL Biomed Inc': 110, 'HZI': 111, 'HeMemics Biotechnologies Inc': 112, 'Helios Bioelectronics': 113, 'HelixBind Inc': 114, 'Hochschule Furtwangen': 115, 'Hospital Ramon y Cajal': 116, 'ICFO': 117, 'ICR': 118, 'IIBR': 119, 'IMEC vzw': 120, 'IMP': 121, 'IMTEK': 122, 'INL': 123, 'ISAR Bioscience GmbH': 124, 'ITE': 125, 'Immundiagnostik AG': 126, 'Immunodiagnostika': 127, 'Immunovia AB': 128, 'Imperial College': 129, 'InDevR Inc': 130, 'InSilixa Inc (Cepheid)': 131, 'Infynity Biomarkers': 132, 'Innobiochips': 133, 'Inside Biometrics Int Ltd': 134, 'Institut Pasteur Paris': 135, 'Institute Curie': 136, 'Institute of Chemistry': 137, 'Instituto SCITEC CNR': 138, 'Instituto de Salud Carlos III': 139, 'Invitae Corporation': 140, 'J-BIO': 141, 'Janssen Pharmaceutica NV': 142, 'Joanneum Research Forschungsgesellschaft': 143, 'Johns Hopkins University': 144, 'K&K Constultant Group Inc': 145, 'Karlsruher Institut für Technologie (KIT)': 146, 'Kephera Diagnostics': 147, 'Keren Instruments': 148, 'Korean Institute of Science and Technology (KIST)': 149, 'LEX Diagnostics Ltd': 150, 'LIST - Luxemburg Institute of Science and Technology': 151, 'LTS Lohmann Therapie-Systeme AG': 152, 'LXRepair SAS': 153, 'Labskin Creations': 154, 'Lawrence Berkeley National Laboratory': 155, 'LifeLineLab s.r.l.': 156, 'Lumensia Sensors': 157, 'Luminex Operation': 158, 'Lund University': 159, 'MBARI': 160, 'MBio Diagnostics Inc': 161, 'MDC BIMSB': 162, 'MIT': 163, 'MPI BPC': 164, 'MPI KGF': 165, 'MSKCC': 166, 'MVZ': 167, 'MagArray Inc': 168, 'Mammoth Biosciences Inc': 169, 'Mayo Foundation - Mayo Clinic Receiving Hub': 170, 'McGill University': 171, 'McMaster Uni': 172, 'Mecwins SA': 173, 'Medical University of Vienna': 174, 'Medtronic': 175, 'Merck Sharp & Dohme Corp': 176, 'MiDIAGNOSTICS': 177, 'Micronit B.V.': 178, 'Microvisk Technologies Ltd': 179, 'Minifab PTY Ltd': 180, 'Mint Diagnostics Ltd': 181, 'Mobidiag Ltd (Hologic)': 182, 'Molecular Assemblies lnc': 183, 'NIH': 184, 'NY Genome Center': 185, 'NanoVation-GS Ltd': 186, 'NanoView Biosciences': 187, 'Nanosynex Ltd': 188, 'Nanyang Technological University': 189, 'New Business International Trading': 190, 'Northeastern University': 191, 'Northwestern University': 192, 'Nypro Limited / DnaNudge': 193, 'Optolane Technologies Inc': 194, 'Ortho Clinical Diagnostics': 195, 'Osler Diagnostics Ltd': 196, 'PCL Inc': 197, 'PSG Procurement Services GmbH': 198, 'Pacific Northwest National Laboratory': 199, 'Palogen': 200, 'Pamgene International B.V.': 201, 'Paratus Diagnostics': 202, 'Phadia AB (Thermo Fisher Scientific)': 203, 'Phillips-Medisize (Molex)': 204, 'Proactive Diagnostics': 205, 'Proteome Sciences R&D GmbH': 206, 'Qorvo Biotechnologies LLC': 207, 'QuantiScienitific  Llc': 208, 'QuantuMDx Group Limited': 209, 'Quantum Design Japan Inc (QDJ)': 210, 'Queen Mary University of London (QMUL)': 211, "Queen's University Belfast": 212, 'Quidel': 213, 'Quotient': 214, 'Quotient Suisse': 215, 'R-Biopharm AG': 216, 'RCPE GmbH': 217, 'RIVM': 218, 'Randox Crumlin': 219, 'Randox Teoranta': 220, 'RayBiotech Inc': 221, 'RayBiotech Life': 222, 'RemAb Therapeutics SL': 223, 'Rice University': 224, 'Robert Bosch GmbH': 225, 'Roche Diagnostics GmbH': 226, 'RosChemAnalitica LLC': 227, 'Rutgers University': 228, 'SF Metsource Ltd': 229, 'SG Medical': 230, 'SLAC National Accelerator Laboratory': 231, 'SQI Diagnostics Systems Inc': 232, 'Safeguard Biosystems Inc': 233, 'Safeguard Biosystems Manufacturing': 234, 'Sanwa Biotech': 235, 'Scienion GmbH': 236, 'Scienion Inc': 237, 'Scienion Ltd': 238, 'Semiotik Llc': 239, 'Shanghai Aifei Electronic Technology Co': 240, 'SiDx Inc': 241, 'Siemens Healthcare Diagnostics': 242, 'Siemens Healthineers Nederland B.V.': 243, 'Spectragenetics': 244, 'Surfix BV': 245, 'Suzhou Epitope Biotechnolgoy Ltd': 246, 'Syngenta Crop Protection AG': 247, 'Synthego': 248, 'TTP plc': 249, 'TU Bergakademie Freiberg': 250, 'TU München': 251, 'Technion Ltd': 252, 'TestLine Clinical Diagnostics s.r.o.': 253, 'The Francis Crick Institute': 254, 'Torus Biosystems Inc': 255, 'UAB Grida': 256, 'UC Berkeley': 257, 'UCL': 258, 'UCSD': 259, 'UCSF': 260, 'UMCG': 261, 'UMG Universitätsmedizin Göttingen': 262, 'Ulster University': 263, 'Uni Bodenkultur': 264, 'Uni Bundeswehr Muenchen': 265, 'Uni Cambridge': 266, 'Uni Edinburgh': 267, 'Uni Georgia': 268, 'Uni Houston': 269, 'Uni Nottingham': 270, 'Uni Oxford': 271, 'Uni Portsmouth': 272, 'Uni Queensland': 273, 'Uni Regenburg': 274, 'Uni Stanford': 275, 'Uni Turku': 276, 'Uni Wageningen': 277, 'Uni Wien': 278, 'Uni Zürich': 279, 'UniSensor S.A.': 280, 'Uniklinik RWTH Aachen': 281, 'Universidad Politechnica de Valencia': 282, 'Universitaetsklinikum Jena': 283, 'Universite Grenoble Alpes': 284, 'University Medical': 285, 'University of Copenhagen': 286, 'University of Liverpool': 287, 'University of Rochester': 288, 'University of Wisconsin': 289, 'University of York': 290, 'Universitätsklinikum Köln': 291, 'Universitätsklinikum Mainz': 292, 'Universitätsmedizin Mannheim': 293, "Université Evry Val d'Essonne": 294, 'Université de Rennes': 295, 'Utrecht University (UMC)': 296, 'VTT Technical Research Centre Finland': 297, 'Vanderbilt University': 298, 'Velocity Sciences': 299, 'Verily Life Sciences': 300, 'Vidya Holdings Ltd': 301, 'Viramed Biotech AG': 302, 'Vitro S.A.': 303, 'WAD GROUP CO. Ltd': 304, 'WAMA Diagnostics SA': 305, 'WWC': 306, 'Weizmann Institute of Science': 307, 'Xsensio SA': 308, 'Z Biotech': 309, 'ZYMOPTIQ': 310, 'Zenostic': 311, 'Zepto Life Technology': 312, 'Zhongke Scientific & Technical Co. Ltd': 313, 'Zhuhai Sinochips Bioscience Co Ltd': 314, 'Zymergen': 315, 'fzmb GmbH': 316, 'iLINE Microsystems S.L.': 317, 'sciCOVIR 19 Projekt': 318}

In [11]:
#create a dictionary for each unique customer
create_dict

{'A*Star Research Entities': 1,
 'ADC': 2,
 'AMC Amsterdam': 3,
 'AMDI Lantana': 4,
 'AMDI Sunflower': 5,
 'AQUARRAY GmbH': 6,
 'AXO Science': 7,
 'Abcam Plc (UK)': 8,
 'Abcam Plc (USA)': 9,
 'Accela': 10,
 'Adarza BioSystems Inc': 11,
 'AerNos Inc': 12,
 'Aesku.Diagnostics GmbH': 13,
 'Alkor Impex Ltd': 14,
 'Altos Labs Inc': 15,
 'Angle Biosiences Inc': 16,
 'Antech Diagnostics': 17,
 'Antelope DX': 18,
 'Anyspectra Scientific Ltd': 19,
 'Applied Microarrays Inc': 20,
 'Aries s.r.l.': 21,
 'Aryballe Technologies': 22,
 'Aselsan Electronic Industries Inc': 23,
 'AstraZeneca UK Ltd': 24,
 'Attomarker Ltd': 25,
 'Automobi Molecular Diagnostice Co. Ltd': 26,
 'BAM - Bundesanstalt für Materialforschung und prüfung': 27,
 'BASF': 28,
 'BCCRC': 29,
 'BMS Cambridge': 30,
 'BRAINBox Solutions Inc': 31,
 'BYU-Provo': 32,
 'Bar-Ilan University': 33,
 'Ben-Gurion University of the Negev': 34,
 'Beth Israel Deaconess Medical Center': 35,
 'Bio Palette Ltd': 36,
 'Bio Rad': 37,
 'BioTT': 38,
 'Biosero Inc': 39,
 'Boehringer Ingelheim': 40,
 'Brigham Young University': 41,
 'Broad Institute': 42,
 'Bruker Optik GmbH': 43,
 'C&D Co': 44,
 'CEA Grenoble': 45,
 'CEA Saclay': 46,
 'CIC biomaGUNE': 47,
 'CNIO': 48,
 'CSIC': 49,
 'CSIC-ICAQ': 50,
 'CSIC-INTA': 51,
 'CTC Analytics AG': 52,
 'California Institute of Technology': 53,
 'Caura.me Ltd': 54,
 'Cedars-Sinai': 55,
 'CellInk AB': 56,
 'CellenCHIP Projekt': 57,
 'Cellenion SASU': 58,
 'Central Scientific Commerce Inc': 59,
 'Chan Zuckerberg BioHub': 60,
 'Changzou Siyao Pharmaceuticals Co. Ltd': 61,
 'Charite': 62,
 "Children's Cancer Institute": 63,
 'Cleverlab Co. Ltd': 64,
 'Community College for Sioux Falls': 65,
 'Cube Dx': 66,
 'D-Tek': 67,
 'DKFZ': 68,
 'DNAe Diagnostics Ltd': 69,
 'DTU Health Tech': 70,
 'Delrus': 71,
 'Dendris': 72,
 'Diarect AG': 73,
 'Dr. Fooke - Achterrath Laboratorien GmbH': 74,
 'Duke University Healthsystems Inc': 75,
 'Dynamic Biosensors GmbH': 76,
 'ENS Paris Saclay': 77,
 'EPFL': 78,
 'EUROCLONE SpA': 79,
 'EWHA Womans University': 80,
 'Earlham Institute': 81,
 'Eastern Virginia Medical School': 82,
 'Ecole Centrale de Lyon': 83,
 'Eindhoven University of Technology': 84,
 'Eli Lilly and Company': 85,
 'Enzyre B.V.': 86,
 'Erasmus MC Rotterdam': 87,
 'Euroimmun AG': 88,
 'European Commission (JRC)': 89,
 'FH Aachen': 90,
 'Flashdx Shenzhen Inc': 91,
 'Fraunhofer CMI': 92,
 'Fraunhofer IZI': 93,
 'Fraunhofer USA': 94,
 'Fred Hutchinson Cancer Center': 95,
 'Fundación Tecnalia Research & Innovation': 96,
 'Future Diagnostics Solutions BV': 97,
 'GENSPEED Biotech GmbH': 98,
 'GenID GmbH': 99,
 'GenMark Diagnostics Inc': 100,
 'Genalyte Inc': 101,
 'Genentech Inc': 102,
 'Gener8 Inc': 103,
 'Genome Sciences Centre': 104,
 'Genomica S.A.U.': 105,
 'Glycan Therapeutics LLC': 106,
 'Grace BioLabs': 107,
 'Greiner Bio-One GmbH': 108,
 'HES-SO': 109,
 'HOIL Biomed Inc': 110,
 'HZI': 111,
 'HeMemics Biotechnologies Inc': 112,
 'Helios Bioelectronics': 113,
 'HelixBind Inc': 114,
 'Hochschule Furtwangen': 115,
 'Hospital Ramon y Cajal': 116,
 'ICFO': 117,
 'ICR': 118,
 'IIBR': 119,
 'IMEC vzw': 120,
 'IMP': 121,
 'IMTEK': 122,
 'INL': 123,
 'ISAR Bioscience GmbH': 124,
 'ITE': 125,
 'Immundiagnostik AG': 126,
 'Immunodiagnostika': 127,
 'Immunovia AB': 128,
 'Imperial College': 129,
 'InDevR Inc': 130,
 'InSilixa Inc (Cepheid)': 131,
 'Infynity Biomarkers': 132,
 'Innobiochips': 133,
 'Inside Biometrics Int Ltd': 134,
 'Institut Pasteur Paris': 135,
 'Institute Curie': 136,
 'Institute of Chemistry': 137,
 'Instituto SCITEC CNR': 138,
 'Instituto de Salud Carlos III': 139,
 'Invitae Corporation': 140,
 'J-BIO': 141,
 'Janssen Pharmaceutica NV': 142,
 'Joanneum Research Forschungsgesellschaft': 143,
 'Johns Hopkins University': 144,
 'K&K Constultant Group Inc': 145,
 'Karlsruher Institut für Technologie (KIT)': 146,
 'Kephera Diagnostics': 147,
 'Keren Instruments': 148,
 'Korean Institute of Science and Technology (KIST)': 149,
 'LEX Diagnostics Ltd': 150,
 'LIST - Luxemburg Institute of Science and Technology': 151,
 'LTS Lohmann Therapie-Systeme AG': 152,
 'LXRepair SAS': 153,
 'Labskin Creations': 154,
 'Lawrence Berkeley National Laboratory': 155,
 'LifeLineLab s.r.l.': 156,
 'Lumensia Sensors': 157,
 'Luminex Operation': 158,
 'Lund University': 159,
 'MBARI': 160,
 'MBio Diagnostics Inc': 161,
 'MDC BIMSB': 162,
 'MIT': 163,
 'MPI BPC': 164,
 'MPI KGF': 165,
 'MSKCC': 166,
 'MVZ': 167,
 'MagArray Inc': 168,
 'Mammoth Biosciences Inc': 169,
 'Mayo Foundation - Mayo Clinic Receiving Hub': 170,
 'McGill University': 171,
 'McMaster Uni': 172,
 'Mecwins SA': 173,
 'Medical University of Vienna': 174,
 'Medtronic': 175,
 'Merck Sharp & Dohme Corp': 176,
 'MiDIAGNOSTICS': 177,
 'Micronit B.V.': 178,
 'Microvisk Technologies Ltd': 179,
 'Minifab PTY Ltd': 180,
 'Mint Diagnostics Ltd': 181,
 'Mobidiag Ltd (Hologic)': 182,
 'Molecular Assemblies lnc': 183,
 'NIH': 184,
 'NY Genome Center': 185,
 'NanoVation-GS Ltd': 186,
 'NanoView Biosciences': 187,
 'Nanosynex Ltd': 188,
 'Nanyang Technological University': 189,
 'New Business International Trading': 190,
 'Northeastern University': 191,
 'Northwestern University': 192,
 'Nypro Limited / DnaNudge': 193,
 'Optolane Technologies Inc': 194,
 'Ortho Clinical Diagnostics': 195,
 'Osler Diagnostics Ltd': 196,
 'PCL Inc': 197,
 'PSG Procurement Services GmbH': 198,
 'Pacific Northwest National Laboratory': 199,
 'Palogen': 200,
 'Pamgene International B.V.': 201,
 'Paratus Diagnostics': 202,
 'Phadia AB (Thermo Fisher Scientific)': 203,
 'Phillips-Medisize (Molex)': 204,
 'Proactive Diagnostics': 205,
 'Proteome Sciences R&D GmbH': 206,
 'Qorvo Biotechnologies LLC': 207,
 'QuantiScienitific  Llc': 208,
 'QuantuMDx Group Limited': 209,
 'Quantum Design Japan Inc (QDJ)': 210,
 'Queen Mary University of London (QMUL)': 211,
 "Queen's University Belfast": 212,
 'Quidel': 213,
 'Quotient': 214,
 'Quotient Suisse': 215,
 'R-Biopharm AG': 216,
 'RCPE GmbH': 217,
 'RIVM': 218,
 'Randox Crumlin': 219,
 'Randox Teoranta': 220,
 'RayBiotech Inc': 221,
 'RayBiotech Life': 222,
 'RemAb Therapeutics SL': 223,
 'Rice University': 224,
 'Robert Bosch GmbH': 225,
 'Roche Diagnostics GmbH': 226,
 'RosChemAnalitica LLC': 227,
 'Rutgers University': 228,
 'SF Metsource Ltd': 229,
 'SG Medical': 230,
 'SLAC National Accelerator Laboratory': 231,
 'SQI Diagnostics Systems Inc': 232,
 'Safeguard Biosystems Inc': 233,
 'Safeguard Biosystems Manufacturing': 234,
 'Sanwa Biotech': 235,
 'Scienion GmbH': 236,
 'Scienion Inc': 237,
 'Scienion Ltd': 238,
 'Semiotik Llc': 239,
 'Shanghai Aifei Electronic Technology Co': 240,
 'SiDx Inc': 241,
 'Siemens Healthcare Diagnostics': 242,
 'Siemens Healthineers Nederland B.V.': 243,
 'Spectragenetics': 244,
 'Surfix BV': 245,
 'Suzhou Epitope Biotechnolgoy Ltd': 246,
 'Syngenta Crop Protection AG': 247,
 'Synthego': 248,
 'TTP plc': 249,
 'TU Bergakademie Freiberg': 250,
 'TU München': 251,
 'Technion Ltd': 252,
 'TestLine Clinical Diagnostics s.r.o.': 253,
 'The Francis Crick Institute': 254,
 'Torus Biosystems Inc': 255,
 'UAB Grida': 256,
 'UC Berkeley': 257,
 'UCL': 258,
 'UCSD': 259,
 'UCSF': 260,
 'UMCG': 261,
 'UMG Universitätsmedizin Göttingen': 262,
 'Ulster University': 263,
 'Uni Bodenkultur': 264,
 'Uni Bundeswehr Muenchen': 265,
 'Uni Cambridge': 266,
 'Uni Edinburgh': 267,
 'Uni Georgia': 268,
 'Uni Houston': 269,
 'Uni Nottingham': 270,
 'Uni Oxford': 271,
 'Uni Portsmouth': 272,
 'Uni Queensland': 273,
 'Uni Regenburg': 274,
 'Uni Stanford': 275,
 'Uni Turku': 276,
 'Uni Wageningen': 277,
 'Uni Wien': 278,
 'Uni Zürich': 279,
 'UniSensor S.A.': 280,
 'Uniklinik RWTH Aachen': 281,
 'Universidad Politechnica de Valencia': 282,
 'Universitaetsklinikum Jena': 283,
 'Universite Grenoble Alpes': 284,
 'University Medical': 285,
 'University of Copenhagen': 286,
 'University of Liverpool': 287,
 'University of Rochester': 288,
 'University of Wisconsin': 289,
 'University of York': 290,
 'Universitätsklinikum Köln': 291,
 'Universitätsklinikum Mainz': 292,
 'Universitätsmedizin Mannheim': 293,
 "Université Evry Val d'Essonne": 294,
 'Université de Rennes': 295,
 'Utrecht University (UMC)': 296,
 'VTT Technical Research Centre Finland': 297,
 'Vanderbilt University': 298,
 'Velocity Sciences': 299,
 'Verily Life Sciences': 300,
 'Vidya Holdings Ltd': 301,
 'Viramed Biotech AG': 302,
 'Vitro S.A.': 303,
 'WAD GROUP CO. Ltd': 304,
 'WAMA Diagnostics SA': 305,
 'WWC': 306,
 'Weizmann Institute of Science': 307,
 'Xsensio SA': 308,
 'Z Biotech': 309,
 'ZYMOPTIQ': 310,
 'Zenostic': 311,
 'Zepto Life Technology': 312,
 'Zhongke Scientific & Technical Co. Ltd': 313,
 'Zhuhai Sinochips Bioscience Co Ltd': 314,
 'Zymergen': 315,
 'fzmb GmbH': 316,
 'iLINE Microsystems S.L.': 317,
 'sciCOVIR 19 Projekt': 318}

After creating the dictionary now we'll use the values for our new column which called customer_id.

In [12]:
#Assign the values from dictionary to a new column 

new_customer_anon_id = []

for customer in customer_df["customer"]:
    new_customer_anon_id.append(create_dict[customer])
    
new_customer_anon_id

customer_df.insert(1, "customer_id", new_customer_anon_id)

COLS **NOT** TO USE:

'PO', 'PO_Inc', 'OC_AG', 'OC_Inc',
'Dummy_Sets', 
'Sci_Ltd', 'Sci_Inc', 'Contract_Manufacturing',
'Machine_Comment'

In [13]:
#Drop these columns: 'PO', 'PO_Inc', 'OC_AG', 'OC_Inc','Dummy_Sets', 'Sci_Ltd', 'Sci_Inc', 'Contract_Manufacturing','Machine_Comment'
customer_df.drop(['po', 'po_inc', 'oc_ag', 'oc_inc','dummy_sets', 'sci_ltd', 'sci_inc', 'contract_manufacturing','machine_comment'], axis = 1, inplace = True)

In [14]:
customer_df.iloc[:10,:]

,customer,customer_id,xdc,size,coating,amount,fitting,date_order,date_delivery_ought,date_delivery_is,delivery_comment,general_comment,division_tag,machine,machine_type,training_kits,channels,delivery_time,locality_country,locality_city,replacement_delivery,replacement_for_id,date_order_month,date_delivery_month,date_order_year,date_delivery_year,finished
0,ADC,2,PDC,80,T2,18.0,S3,2018-11-30,2019-02-15,2021-03-05,Part 1,Teil 1 zusammen mit 12x OEM's + 24 Dummy Sets...,NaN,1.0,OEM,NaN,NaN,826.0,UK,Witney,NaN,NaN,2018-11,2021-03,2018.0,2021.0,1
1,ADC,2,PDC,80,T2,18.0,S3,2018-11-30,NaN,2021-03-15,Part 2,Teil 2 zusammen mit 12x OEM's + 24 Dummy Sets...,NaN,1.0,OEM,NaN,NaN,836.0,UK,Witney,NaN,NaN,2018-11,2021-03,2018.0,2021.0,1
2,Optolane Technologies Inc,194,PDC,90,T1,10.0,S5/S11,2019-03-19,NaN,2020-01-31,Dez.,zusammen mit S100-Rocket I Portal Upgrade (10...,NaN,1.0,S100,NaN,10,318.0,South Korea,Seongnam-si (Gyeonggi-do),NaN,NaN,2019-03,2020-01,2019.0,2020.0,1
3,MDC BIMSB,162,PDC-C,CS,NaN,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,NaN,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1
4,MDC BIMSB,162,PDC-C,CM,NaN,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,NaN,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1
5,MDC BIMSB,162,PDC-C,CL,NaN,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,NaN,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1
6,Scienion Inc,237,PDC-C,CS,NaN,3.0,S5/S11,2019-06-03,NaN,2020-03-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,277.0,USA,Tempe,NaN,NaN,2019-06,2020-03,2019.0,2020.0,1
7,Scienion Inc,237,PDC-C,CL,NaN,3.0,S5/S11,2019-06-03,NaN,2020-03-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,277.0,USA,Tempe,NaN,NaN,2019-06,2020-03,2019.0,2020.0,1
8,Scienion Inc,237,PDC,50,T1,2.0,S5/S11,2019-06-03,NaN,2020-12-17,NaN,Rest= 6x FAT PDC,NaN,NaN,NaN,NaN,NaN,563.0,USA,Tempe,NaN,NaN,2019-06,2020-12,2019.0,2020.0,1
9,Scienion Inc,237,PDC,50,T2,1.0,S5/S11,2019-06-03,NaN,2020-08-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450.0,USA,Tempe,NaN,NaN,2019-06,2020-08,2019.0,2020.0,1

In [15]:
#find the unique values in XDC column
customer_df['xdc'].unique()

array(['PDC', 'PDC-C', 'NDC'], dtype=object)

In [16]:
#rename the misspelled value with the original version
customer_df['xdc'] = customer_df['xdc'].replace(['PDC80'],['PDC'])
customer_df['xdc'].unique()

array(['PDC', 'PDC-C', 'NDC'], dtype=object)

## Anonymise the Values  and Change nan Values

customer name --> new column ==> customer IDs

[XDC] PDC / PDC-C / NDC --> P1, P2, P3 | DONE

XDC --> new column ==> NOZ

[Size] 50 / 60 / 70 / 80 / 90 / 100 --> 00 / 10 / 20 / 30 / 40 / 50

[Size] CS / CM / CL --> C1 / C2 / C3

[Size] NL / NM / NH --> N1 / N2 / N3

[Size] N200 / N300 / N400 --> N4 / N5 / N6

[Size] sN100 / sN200 / sN300 / sN400 / sN500 --> N7 / N8 / N9 / N10 / N11

[Size] SolB / FAT / H2O / Dummy / Training  -->  X1 / X2 / X3 / X4 / X5

[Coating] T0 / T1 / T2 / T3 / T4 / T1sym --> B0 / B1 / B2 / B3 / B4 / B5

XDC --> new column ==> Modification

Machine_types --> 'S3' / 'S3 NANO' / 'S12' / 'SX' / 'SX NANO' / 'S100'/ 'CO' / 'CO F1.1' / 'CO F1.4' / 'CO F1.4 BSC' / 'CO X1' / 'spheroONE' / 'OEM'    	-->		    M1  / M1N  / M2  / M3  / M3N  / M4  /  M5 / M6  / M7  / M7B  /  M8  /  M9  /  M0

### Anonymise Values in XDC Column

Since we can't use our original data we need to anonymise the values in the columns.

[XDC] PDC / PDC-C / NDC --> P1, P2, P3 | DONE

XDC --> new column ==> product_family

In [17]:
#Create new anonymise column for XDC(product) and name it product_family and anonymise the values.
customer_df.insert(3, 'product_family', customer_df['xdc']) 
customer_df['product_family'] = customer_df['product_family'].replace(['PDC', 'PDC-C', 'NDC'],['P1', 'P2', 'P3'])
customer_df['product_family']

0       P1
1       P1
2       P1
3       P2
4       P2
        ..
2782    P1
2783    P1
2784    P1
2785    P1
2786    P1
Name: product_family, Length: 2787, dtype: object

### Anonymise Values in Size Column

[Size] 50 / 60 / 70 / 80 / 90 / 100 --> 00 / 10 / 20 / 30 / 40 / 50

[Size] CS / CM / CL --> C1 / C2 / C3

[Size] NL / NM / NH --> N1 / N2 / N3

[Size] N200 / N300 / N400 --> N4 / N5 / N6

[Size] sN100 / sN200 / sN300 / sN400 / sN500 --> N7 / N8 / N9 / N10 / N11

[Size] SolB / FAT / H2O / Dummy / Training  -->  X1 / X2 / X3 / X4 / X5

In [18]:
#Unique values in Size Category
customer_df['size'].unique()

array(['80', '90', 'CS', 'CM', 'CL', '50', '70', '60', '100', 'SolB',
       'Dummy', 'NL', 'NM', 'NH', 'FAT', 'H2O', 'Training', 'N300',
       'N400', 'N200', 'CN', 'sN100', 'sN200', 'sN300', 'sN400', 'sN500'],
      dtype=object)

In [19]:
customer_df.insert(4, 'size_new', customer_df['size'])

In [20]:
#Created new column for anonymising the values in Size column
customer_df['size_new'] = customer_df['size_new'].replace(['50', '60', '70', '80', '90', '100', 'CS', 'CM', 'CL', 'NL', 'NM', 'NH', 'N200', 'N300', 'N400', 'sN100', 'sN200', 'sN300', 'sN400', 'sN500', 'SolB', 'FAT', 'H2O', 'Dummy', 'Training'],['00', '10', '20', '30', '40', '50', 'C1', 'C2', 'C3', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10', 'N11', 'X1', 'X2', 'X3', 'X4', 'X5'])
customer_df['size_new']

0       30
1       30
2       40
3       C1
4       C2
        ..
2782    30
2783    30
2784    30
2785    30
2786    30
Name: size_new, Length: 2787, dtype: object

### Anonymise Values in Coating

[Coating] T0 / T1 / T2 / T3 / T4 / T1sym --> B0 / B1 / B2 / B3 / B4 / B5

In [21]:
customer_df['coating'].unique()

array(['T2', 'T1', nan, 'T4', 'T3', 'T1sym'], dtype=object)

In [22]:
customer_df['coating'] = customer_df['coating'].fillna('T0')
customer_df['coating']

0       T2
1       T2
2       T1
3       T0
4       T0
        ..
2782    T2
2783    T0
2784    T0
2785    T2
2786    T1
Name: coating, Length: 2787, dtype: object

In [23]:
customer_df['coating'] = customer_df['coating'].replace(['0'],['T0'])
customer_df['coating'].unique()

array(['T2', 'T1', 'T0', 'T4', 'T3', 'T1sym'], dtype=object)

In [24]:
customer_df.insert(6, 'coating_new', customer_df['coating'])

In [25]:
#Created new category to anonymise the values in Coating as we can see how the values changed : Coating T0 / T1 / T2 / T3 / T4 / T1sym --> B0 / B1 / B2 / B3 / B4 / B5
customer_df['coating_new'] = customer_df['coating_new'].replace(['T0', 'T1', 'T2', 'T3', 'T4', 'T1sym'],['B0', 'B1', 'B2', 'B3', 'B4', 'B5'])
customer_df['coating_new']

0       B2
1       B2
2       B1
3       B0
4       B0
        ..
2782    B2
2783    B0
2784    B0
2785    B2
2786    B1
Name: coating_new, Length: 2787, dtype: object

### Anonymise Values in Machine Type

[Machine_types] --> 'S3' / 'S3 NANO' / 'S12' / 'SX' / 'SX NANO' / 'S100'/ 'CO' / 'CO F1.1' / 'CO F1.4' / 'CO F1.4 BSC' / 'CO X1' / 'spheroONE' / 'OEM'    	-->		    M1  / M1N  / M2  / M3  / M3N  / M4  /  M5 / M6  / M7  / M7B  /  M8  /  M9  /  M0

In [26]:
#check the non values in machine_type
customer_df['machine_type'].unique()

array(['OEM', 'S100', nan, 'CO F1.4', 'SX', 'S12', 'S3', 'CO', 'CO F1.1',
       'S5/S11', 'CO X1', 'CO F1.4 BSC', 'S3-2', 'SX NANO', 'spheroONE',
       'S3 NANO'], dtype=object)

In [27]:
#replace nan values with 0
customer_df['machine_type'] = customer_df['machine_type'].fillna('none')
customer_df['machine_type'].unique()

array(['OEM', 'S100', 'none', 'CO F1.4', 'SX', 'S12', 'S3', 'CO',
       'CO F1.1', 'S5/S11', 'CO X1', 'CO F1.4 BSC', 'S3-2', 'SX NANO',
       'spheroONE', 'S3 NANO'], dtype=object)

In [28]:
customer_df['machine_type'] = customer_df['machine_type'].replace(['S3', 'S3 NANO', 'S12', 'SX', 'SX NANO', 'S100', 'CO', 'CO F1.1', 'CO F1.4', 'CO F1.4 BSC', 'S3-2', 'CO X1', 'spheroONE', 'OEM', 'S5/S11'],['M1', 'M1N', 'M2', 'M3', 'M3N', 'M4', 'M5', 'M6', 'M7', 'M7B', 'M1', 'M8', 'M9', 'M0', 'not a machine'])
customer_df['machine_type'].unique()

array(['M0', 'M4', 'none', 'M7', 'M3', 'M2', 'M1', 'M5', 'M6',
       'not a machine', 'M8', 'M7B', 'M3N', 'M9', 'M1N'], dtype=object)

### Create a New Column For Product Name (Version)

To concate product family, size_new and coating_new we'll create a final product name under version column.

In [29]:
# A new column to concate all three columns with the anonymised data
version = []
for idx in range(len(customer_df['size_new'])):
    string = customer_df["product_family"][idx] + "_" + customer_df["size_new"][idx] + "_" + customer_df["coating_new"][idx]
    print(string)
    version.append(string)

P1_30_B2
P1_30_B2
P1_40_B1
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C1_B0
P2_C3_B0
P1_00_B1
P1_00_B2
P1_40_B2
P1_40_B4
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_40_B0
P1_40_B4
P1_30_B2
P1_30_B3
P1_20_B0
P1_00_B3
P1_00_B2
P1_30_B2
P2_C2_B0
P1_30_B2
P1_30_B2
P2_C1_B0
P2_C1_B0
P2_C2_B0
P2_C2_B0
P2_C3_B0
P2_C2_B0
P1_10_B0
P1_30_B0
P1_40_B0
P1_30_B2
P1_00_B4
P1_20_B1
P1_10_B0
P1_10_B1
P1_40_B2
P1_00_B0
P1_10_B4
P1_30_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B3
P1_20_B1
P1_20_B0
P1_20_B0
P1_40_B2
P1_20_B1
P1_20_B2
P1_50_B1
P1_50_B2
P1_50_B3
P1_50_B4
P1_40_B2
P1_20_B2
P1_30_B1
P2_C2_B0
P2_C2_B0
P1_00_B0
P1_20_B2
P1_00_B4
P1_30_B0
P1_20_B4
P1_20_B1
P1_10_B0
P1_40_B0
P1_20_B0
P2_C3_B0
P2_C1_B0
P2_C2_B0
P1_50_B3
P1_00_B4
P1_00_B4
P1_00_B0
P1_20_B1
P1_40_B3
P1_30_B0
P1_20_B3
P1_30_B2
P1_30_B2
P1_30_B0
P1_30_B0
P1_30_B3
P1_20_B3
P1_30_B2
P1_30_B2
P1_30_B1
P1_30_B2
P1_30_B2
P1_30_B3
P2_C2_B0
P2_C3_B0
P1_30_B2
P1_30_B3
P1_30_B4
P1_30_B2
P1_30_B2
P1_30_B4
P2_C2_B0
P1_30_B2
P2_C2_B0
P1_20_B3
P2_C2_B0
P1_20_B4
P1_10_B4
P1_20_B0
P1_20_B2
P2_C2_B0
P2_C2_B0
P1_20_B4
P1_00_B1
P1_30_B3
P2_C2_B0
P1_X1_B0
P2_C2_B0
P2_C3_B0
P2_C2_B0
P1_30_B0
P1_00_B2
P1_00_B3
P1_20_B2
P1_30_B3
P2_C2_B0
P1_40_B3
P1_30_B0
P1_40_B3
P1_20_B0
P1_00_B0
P1_10_B1
P1_50_B3
P1_30_B4
P2_C2_B0
P1_00_B0
P1_10_B2
P1_30_B1
P1_20_B2
P2_C2_B0
P1_30_B2
P2_C2_B0
P1_40_B3
P1_40_B3
P1_40_B1
P1_40_B2
P1_40_B3
P1_20_B1
P1_30_B0
P1_20_B1
P1_40_B3
P1_20_B3
P1_20_B0
P1_30_B3
P1_40_B0
P1_X1_B0
P1_40_B0
P1_10_B4
P1_10_B3
P1_20_B1
P2_C2_B0
P2_C1_B0
P1_20_B1
P1_20_B4
P2_C2_B0
P2_C1_B0
P1_40_B1
P1_00_B0
P1_30_B1
P2_C2_B0
P1_30_B2
P1_30_B2
P1_10_B4
P1_20_B3
P1_20_B0
P2_C2_B0
P2_C1_B0
P1_10_B0
P1_20_B0
P1_20_B2
P1_20_B2
P1_30_B0
P1_30_B3
P2_C1_B0
P1_40_B0
P2_C3_B0
P1_20_B3
P1_40_B2
P1_20_B3
P1_20_B4
P1_20_B1
P1_20_B0
P1_20_B3
P1_30_B3
P1_30_B2
P1_40_B4
P1_20_B2
P1_20_B2
P1_40_B2
P1_20_B4
P2_C2_B0
P2_C2_B0
P1_20_B1
P1_20_B2
P2_C2_B0
P1_30_B0
P2_C2_B0
P1_10_B2
P1_10_B1
P1_10_B2
P1_10_B2
P1_10_B4
P1_20_B3
P1_20_B0
P1_40_B1
P1_20_B0
P1_30_B2
P1_20_B1
P1_30_B0
P1_20_B1
P1_20_B1
P2_C2_B0
P1_30_B2
P1_30_B1
P1_10_B1
P2_C2_B0
P1_20_B3
P1_40_B0
P2_C2_B0
P2_C2_B0
P2_C2_B2
P2_C2_B4
P2_C2_B2
P2_C2_B4
P1_X1_B0
P1_20_B3
P1_40_B0
P1_30_B4
P1_20_B1
P1_10_B1
P1_10_B3
P2_C2_B0
P1_30_B0
P2_C2_B0
P1_30_B0
P2_C2_B0
P1_30_B0
P2_C2_B0
P1_30_B0
P2_C2_B0
P1_30_B0
P1_10_B1
P1_20_B1
P1_40_B0
P1_40_B3
P1_40_B3
P1_20_B3
P1_30_B1
P1_00_B0
P1_20_B0
P1_30_B0
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C2_B2
P2_C2_B3
P2_C2_B4
P1_10_B3
P1_20_B3
P1_30_B3
P2_C1_B0
P2_C2_B0
P1_00_B0
P2_C2_B0
P1_20_B0
P1_30_B0
P1_30_B1
P1_30_B4
P1_40_B0
P1_30_B2
P1_20_B2
P1_30_B4
P1_20_B0
P1_00_B1
P1_20_B0
P1_30_B3
P1_10_B4
P1_20_B4
P1_20_B4
P1_20_B1
P1_20_B3
P1_30_B0
P1_30_B2
P2_C2_B0
P1_00_B0
P1_30_B0
P1_30_B0
P1_30_B0
P1_30_B0
P1_10_B4
P1_30_B2
P1_30_B1
P1_20_B1
P1_30_B2
P1_20_B1
P1_30_B2
P1_20_B1
P1_20_B1
P1_20_B3
P1_30_B2
P1_20_B0
P1_30_B2
P1_30_B2
P1_20_B0
P1_30_B2
P1_20_B3
P1_30_B4
P1_30_B1
P2_C2_B0
P2_C3_B0
P1_10_B1
P1_10_B3
P1_20_B3
P1_40_B3
P1_30_B3
P1_20_B0
P1_40_B0
P2_C1_B0
P1_20_B0
P1_20_B1
P1_20_B3
P1_20_B4
P1_00_B4
P1_30_B0
P1_10_B4
P1_30_B2
P1_30_B1
P1_20_B1
P1_40_B0
P1_30_B3
P1_20_B3
P2_C2_B0
P1_00_B0
P1_20_B4
P1_20_B1
P1_20_B0
P1_X1_B0
P1_20_B3
P1_30_B1
P1_30_B1
P1_40_B0
P1_30_B0
P1_30_B0
P1_20_B1
P1_20_B4
P1_10_B1
P1_20_B1
P1_20_B1
P1_20_B0
P1_30_B2
P1_30_B0
P1_20_B1
P1_10_B4
P1_30_B2
P1_30_B1
P1_20_B1
P1_30_B4
P1_30_B2
P1_30_B1
P1_20_B2
P1_00_B4
P1_10_B2
P2_C2_B0
P1_00_B2
P1_30_B2
P1_40_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_40_B2
P1_20_B0
P1_20_B1
P1_20_B3
P1_30_B1
P1_30_B4
P1_20_B2
P1_20_B3
P2_C2_B0
P1_30_B4
P1_40_B2
P1_40_B0
P1_20_B0
P1_20_B0
P1_10_B0
P1_00_B0
P1_10_B4
P1_30_B1
P1_20_B1
P1_30_B2
P1_10_B4
P1_30_B1
P1_20_B1
P1_20_B2
P1_20_B2
P2_C2_B0
P1_20_B0
P1_20_B1
P1_20_B2
P1_20_B3
P1_20_B4
P1_20_B3
P1_30_B3
P1_20_B3
P1_10_B0
P1_30_B3
P1_30_B4
P1_30_B2
P1_20_B3
P1_30_B2
P2_C3_B0
P1_30_B3
P1_40_B3
P1_40_B0
P1_20_B2
P1_30_B2
P1_30_B3
P1_30_B2
P1_30_B1
P1_30_B3
P1_40_B4
P1_20_B1
P1_20_B2
P1_30_B2
P1_30_B2
P1_20_B0
P1_30_B0
P1_20_B0
P1_20_B4
P1_30_B3
P1_20_B0
P1_30_B3
P1_20_B4
P1_40_B4
P2_C2_B0
P1_20_B3
P1_40_B0
P1_30_B4
P1_30_B4
P1_30_B1
P1_40_B3
P1_40_B1
P1_40_B3
P1_10_B4
P1_30_B2
P1_20_B1
P1_30_B4
P1_20_B1
P1_00_B2
P2_C2_B0
P2_C2_B0
P1_X1_B0
P1_20_B1
P1_40_B1
P1_20_B0
P1_00_B1
P1_10_B4
P1_30_B2
P2_C1_B0
P1_00_B0
P1_20_B3
P1_20_B0
P1_30_B4
P1_40_B2
P1_00_B0
P1_20_B0
P1_20_B2
P1_20_B3
P1_20_B4
P1_30_B3
P1_40_B4
P1_20_B0
P1_00_B0
P1_10_B3
P1_20_B4
P1_20_B1
P1_30_B1
P1_20_B1
P1_30_B4
P1_20_B1
P1_30_B2
P1_30_B2
P1_10_B4
P1_30_B1
P1_20_B1
P1_10_B4
P1_30_B4
P1_30_B2
P1_20_B1
P1_30_B2
P1_30_B1
P1_20_B1
P1_30_B4
P1_10_B4
P1_20_B1
P1_00_B2
P1_50_B4
P1_20_B1
P1_20_B0
P1_20_B1
P1_20_B0
P1_20_B1
P1_20_B4
P2_C2_B0
P1_20_B1
P1_30_B2
P1_30_B3
P1_30_B0
P1_30_B1
P1_30_B1
P1_10_B1
P1_10_B3
P1_10_B4
P1_10_B0
P2_C3_B0
P1_X1_B0
P1_40_B0
P1_30_B2
P1_20_B1
P1_20_B2
P1_00_B1
P1_X4_B0
P2_C2_B0
P1_30_B3
P1_00_B1
P1_20_B3
P2_C2_B0
P2_C2_B0
P2_C2_B0
P2_C2_B0
P1_40_B0
P1_20_B3
P1_20_B3
P1_30_B2
P1_30_B3
P2_C2_B0
P2_C3_B0
P1_30_B2
P1_50_B4
P1_20_B3
P1_30_B4
P1_20_B2
P2_C2_B0
P2_C3_B0
P1_20_B4
P1_20_B2
P2_C1_B0
P1_00_B2
P1_00_B3
P1_20_B2
P1_30_B3
P1_20_B0
P2_C2_B0
P1_40_B4
P1_20_B1
P1_30_B2
P1_10_B0
P1_30_B3
P1_20_B2
P1_20_B2
P1_40_B2
P2_C2_B0
P2_C3_B0
P1_20_B3
P1_30_B0
P1_20_B4
P1_X1_B0
P1_40_B1
P1_20_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B1
P1_20_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B1
P1_20_B2
P1_30_B2
P1_20_B4
P1_20_B1
P1_20_B2
P1_20_B2
P1_20_B1
P1_20_B4
P2_C2_B0
P2_C1_B0
P2_C2_B0
P1_10_B3
P1_30_B1
P1_10_B0
P1_40_B0
P1_30_B4
P1_20_B0
P1_30_B3
P1_20_B1
P1_20_B3
P1_20_B4
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_20_B1
P1_20_B1
P1_10_B2
P1_10_B2
P1_20_B2
P1_20_B3
P1_40_B3
P1_20_B0
P1_20_B1
P1_20_B0
P1_40_B0
P1_20_B0
P1_20_B0
P1_20_B0
P1_40_B3
P1_40_B1
P1_40_B3
P1_40_B1
P2_C2_B0
P1_20_B1
P1_40_B3
P1_50_B3
P1_20_B0
P1_20_B1
P1_20_B4
P1_20_B0
P1_40_B0
P1_30_B1
P1_20_B0
P1_30_B2
P1_30_B2
P1_30_B3
P1_00_B1
P1_30_B4
P1_30_B3
P1_20_B4
P2_C2_B0
P1_20_B2
P1_20_B1
P1_20_B4
P1_20_B1
P1_20_B0
P1_20_B1
P1_20_B3
P1_20_B4
P1_10_B0
P1_20_B0
P2_C2_B0
P2_C3_B0
P1_10_B3
P2_C3_B0
P1_30_B1
P1_20_B3
P1_20_B0
P1_30_B2
P1_20_B1
P1_20_B3
P2_C2_B0
P1_40_B0
P1_20_B0
P1_20_B1
P1_40_B2
P1_50_B2
P1_50_B0
P1_00_B2
P2_C2_B0
P1_20_B0
P1_30_B3
P1_20_B2
P1_30_B2
P1_20_B4
P1_20_B3
P1_40_B2
P2_C2_B0
P1_20_B0
P2_C3_B0
P1_20_B1
P1_20_B4
P1_20_B1
P1_20_B1
P1_20_B3
P1_30_B4
P1_30_B4
P1_40_B3
P1_40_B3
P1_20_B2
P1_X1_B0
P1_40_B0
P1_20_B3
P1_10_B3
P1_40_B3
P1_20_B3
P1_20_B0
P1_30_B0
P3_N1_B2
P3_N2_B2
P3_N3_B2
P1_40_B3
P1_30_B2
P1_40_B0
P2_C2_B0
P1_30_B1
P2_C2_B0
P2_C3_B0
P1_00_B0
P1_00_B2
P1_00_B2
P1_30_B0
P1_30_B2
P1_30_B3
P1_30_B4
P2_C2_B0
P2_C3_B4
P2_C3_B3
P2_C2_B0
P2_C1_B0
P1_40_B4
P1_20_B0
P1_20_B0
P1_20_B0
P1_20_B2
P1_20_B0
P3_N2_B2
P1_20_B1
P2_C2_B0
P2_C3_B0
P1_20_B0
P1_30_B2
P1_20_B1
P1_20_B0
P1_20_B3
P2_C2_B0
P1_20_B0
P1_20_B0
P2_C2_B0
P1_00_B2
P1_20_B1
P1_20_B4
P1_10_B1
P1_20_B1
P1_30_B1
P1_30_B4
P1_20_B0
P1_00_B1
P1_20_B1
P1_20_B0
P1_20_B0
P1_40_B2
P2_C2_B0
P1_30_B3
P1_20_B3
P2_C2_B0
P1_20_B3
P1_20_B0
P2_C2_B0
P1_20_B1
P1_10_B4
P1_40_B1
P1_40_B3
P1_40_B4
P2_C3_B0
P1_00_B2
P1_30_B2
P1_20_B2
P1_20_B1
P1_20_B1
P1_10_B4
P1_10_B4
P1_30_B0
P1_10_B2
P1_20_B2
P2_C2_B0
P1_10_B4
P1_10_B4
P1_40_B0
P1_00_B3
P1_20_B2
P1_20_B1
P1_30_B4
P1_20_B2
P1_40_B1
P1_30_B3
P1_30_B1
P1_20_B4
P1_20_B2
P1_X4_B0
P1_20_B2
P1_40_B4
P1_30_B0
P1_30_B4
P1_30_B4
P1_40_B0
P1_20_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B1
P1_20_B1
P1_10_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B0
P1_20_B3
P1_20_B1
P1_20_B3
P1_30_B2
P1_30_B2
P1_40_B2
P1_20_B0
P1_40_B3
P2_C1_B0
P1_30_B4
P1_30_B0
P1_20_B3
P1_20_B1
P1_30_B0
P1_30_B4
P3_N2_B2
P3_N1_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B0
P1_30_B3
P1_30_B1
P1_30_B2
P1_30_B3
P1_40_B2
P1_30_B0
P1_20_B0
P1_30_B3
P1_30_B1
P1_30_B2
P1_40_B0
P1_30_B3
P1_40_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_20_B1
P2_C2_B0
P1_20_B3
P1_50_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_10_B0
P1_10_B0
P1_30_B2
P1_30_B2
P1_20_B2
P1_X2_B0
P1_X2_B0
P1_X2_B0
P1_X2_B0
P1_X2_B0
P1_X2_B0
P1_30_B0
P1_20_B3
P1_30_B3
P1_30_B0
P1_30_B0
P1_30_B0
P2_C1_B0
P2_C1_B0
P1_20_B3
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_10_B1
P1_40_B3
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_20_B0
P1_20_B3
P1_20_B3
P1_20_B4
P1_20_B0
P1_20_B1
P1_40_B3
P1_40_B0
P2_C2_B0
P2_C3_B0
P2_C2_B0
P2_C3_B0
P1_20_B2
P1_30_B1
P1_20_B2
P1_20_B1
P1_20_B3
P1_30_B0
P1_X4_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B1
P1_30_B2
P2_C2_B0
P1_30_B2
P1_30_B0
P1_30_B3
P1_20_B1
P1_20_B2
P1_20_B1
P1_20_B1
P1_30_B1
P1_20_B1
P1_20_B1
P1_20_B0
P1_20_B0
P1_30_B0
P1_10_B2
P1_20_B1
P1_20_B0
P2_C3_B0
P1_X3_B0
P1_10_B0
P1_30_B2
P1_30_B4
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B2
P1_40_B3
P1_40_B3
P2_C2_B0
P1_50_B4
P1_20_B3
P1_20_B4
P1_40_B1
P1_20_B0
P1_30_B2
P1_30_B2
P1_20_B3
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_30_B4
P1_30_B4
P1_30_B4
P1_30_B4
P1_30_B4
P2_C1_B0
P1_20_B1
P1_20_B2
P1_20_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B3
P1_20_B0
P1_30_B1
P1_30_B1
P1_30_B2
P1_20_B1
P2_C2_B0
P1_20_B1
P1_20_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B2
P1_30_B2
P1_30_B3
P1_50_B4
P1_50_B2
P1_20_B3
P1_20_B0
P1_20_B2
P1_20_B4
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_30_B3
P1_20_B1
P1_30_B3
P2_C3_B0
P1_20_B1
P1_30_B2
P1_40_B3
P2_C2_B0
P1_30_B0
P1_20_B2
P1_20_B3
P1_X4_B0
P1_X2_B0
P1_10_B4
P1_20_B4
P1_30_B0
P2_C2_B0
P2_C3_B0
P2_C2_B0
P2_C2_B0
P2_C1_B0
P1_40_B1
P1_40_B4
P1_20_B1
P2_C2_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B0
P1_30_B2
P1_30_B2
P1_40_B3
P1_X1_B0
P1_20_B1
P1_40_B0
P1_20_B0
P1_10_B1
P1_30_B2
P1_30_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B1
P1_30_B1
P1_40_B3
P1_20_B1
P1_20_B2
P1_20_B4
P1_20_B4
P2_C2_B0
P1_10_B4
P1_10_B4
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B1
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B1
P1_20_B1
P1_30_B2
P2_C3_B0
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_30_B0
P1_30_B0
P1_30_B0
P1_20_B2
P1_30_B1
P1_X4_B0
P1_X4_B0
P2_C2_B0
P1_20_B0
P1_30_B2
P1_20_B1
P1_20_B1
P2_C2_B0
P3_N2_B2
P2_C3_B0
P1_30_B2
P1_20_B3
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C2_B3
P2_C3_B3
P1_20_B3
P1_30_B0
P1_30_B3
P1_50_B4
P1_30_B2
P1_30_B0
P1_20_B4
P1_20_B2
P1_20_B3
P1_20_B0
P1_10_B0
P1_10_B4
P1_30_B0
P1_30_B4
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B0
P1_20_B1
P1_30_B2
P1_30_B1
P1_30_B1
P1_30_B2
P1_30_B0
P1_30_B2
P1_30_B3
P1_20_B4
P1_30_B0
P1_10_B0
P1_20_B0
P1_20_B0
P1_20_B0
P1_20_B0
P1_20_B0
P1_20_B0
P1_30_B0
P1_40_B0
P1_30_B0
P1_X4_B0
P1_20_B1
P1_30_B0
P1_30_B2
P1_40_B2
P1_50_B4
P1_30_B4
P1_20_B1
P1_20_B1
P1_20_B2
P1_20_B3
P2_C1_B0
P2_C2_B0
P1_30_B0
P2_C2_B0
P2_C2_B0
P2_C3_B0
P1_20_B4
P2_C3_B3
P1_30_B3
P1_20_B1
P3_N1_B2
P3_N2_B2
P3_N3_B2
P1_30_B2
P1_30_B0
P1_20_B4
P1_40_B4
P1_50_B4
P1_20_B2
P2_C1_B0
P2_C2_B0
P1_30_B0
P1_30_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B0
P1_50_B3
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_20_B2
P1_30_B4
P2_C2_B0
P2_C3_B0
P1_10_B4
P1_20_B1
P2_C2_B0
P1_20_B1
P1_20_B2
P1_20_B1
P1_20_B3
P1_20_B0
P1_30_B0
P1_40_B4
P1_30_B2
P1_20_B1
P1_20_B4
P2_C2_B0
P1_30_B2
P1_10_B3
P1_20_B3
P3_N1_B2
P1_30_B2
P1_30_B2
P1_10_B0
P1_40_B2
P1_30_B1
P1_20_B1
P1_20_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_40_B3
P1_50_B3
P1_20_B2
P1_30_B0
P1_30_B1
P1_20_B4
P1_50_B4
P1_20_B4
P1_50_B4
P1_20_B4
P1_50_B4
P1_20_B4
P1_50_B4
P2_C1_B0
P2_C2_B0
P2_C3_B0
P3_N1_B2
P3_N2_B2
P3_N3_B2
P1_X1_B0
P1_30_B2
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_30_B2
P1_X2_B0
P1_10_B2
P1_10_B4
P1_10_B0
P1_40_B4
P1_20_B1
P1_20_B0
P3_N1_B2
P3_N2_B2
P1_20_B1
P1_30_B0
P1_30_B2
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_10_B1
P1_20_B1
P1_20_B4
P1_20_B2
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_50_B0
P1_X2_B0
P1_20_B4
P1_40_B4
P1_30_B1
P2_C2_B0
P1_20_B1
P1_20_B1
P1_20_B1
P1_00_B1
P2_C2_B0
P1_40_B0
P1_30_B1
P1_30_B1
P1_30_B1
P1_20_B1
P1_20_B2
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C1_B0
P2_C3_B3
P1_10_B3
P1_10_B4
P1_20_B0
P1_30_B0
P1_10_B2
P1_30_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B0
P1_20_B1
P1_10_B1
P1_10_B3
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B4
P2_C3_B0
P2_C2_B0
P1_20_B2
P1_30_B1
P1_30_B2
P1_20_B0
P1_20_B0
P1_40_B2
P1_30_B2
P1_30_B2
P1_30_B4
P1_20_B4
P1_20_B4
P1_40_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B1
P1_30_B1
P2_C2_B0
P1_20_B4
P2_C2_B0
P1_20_B0
P1_20_B2
P1_10_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B2
P1_20_B1
P1_20_B1
P2_C1_B0
P2_C2_B0
P1_20_B2
P2_C1_B0
P2_C2_B0
P1_30_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B1
P1_40_B2
P1_40_B2
P1_30_B4
P1_20_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B0
P1_30_B0
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B2
P1_10_B2
P1_20_B2
P1_30_B3
P1_30_B4
P2_C2_B0
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C1_B0
P2_C2_B0
P1_20_B0
P1_30_B0
P1_50_B0
P2_C3_B3
P3_N3_B2
P1_20_B4
P1_40_B3
P1_30_B1
P1_20_B2
P2_C2_B0
P1_20_B1
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B3
P1_20_B2
P1_10_B2
P1_10_B3
P1_30_B2
P1_30_B3
P1_20_B4
P1_20_B3
P1_10_B1
P1_10_B0
P1_30_B3
P1_30_B3
P1_10_B1
P1_10_B1
P1_10_B1
P1_10_B1
P1_10_B1
P1_10_B1
P1_10_B1
P1_30_B4
P1_10_B1
P1_30_B2
P1_30_B2
P2_C3_B0
P1_20_B1
P1_20_B2
P1_20_B2
P1_20_B4
P2_C3_B0
P1_10_B1
P1_10_B3
P1_X3_B0
P1_20_B1
P1_30_B1
P1_30_B4
P1_30_B2
P1_10_B1
P1_20_B3
P1_30_B4
P1_X1_B0
P1_20_B3
P1_40_B2
P1_50_B3
P1_10_B4
P2_C2_B0
P1_30_B1
P1_30_B1
P1_10_B0
P1_10_B1
P1_10_B2
P1_10_B3
P1_10_B4
P1_40_B4
P1_20_B2
P1_20_B0
P1_30_B1
P1_30_B0
P1_40_B0
P2_C2_B0
P2_C3_B0
P1_30_B0
P2_C2_B0
P2_C3_B0
P1_30_B0
P1_20_B1
P1_30_B2
P1_20_B1
P1_30_B2
P1_30_B2
P1_20_B1
P2_C2_B0
P1_X1_B0
P1_30_B2
P1_30_B3
P1_20_B2
P1_10_B1
P1_20_B1
P1_10_B3
P1_20_B1
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P1_10_B0
P1_X5_B0
P1_20_B4
P1_10_B1
P1_30_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B4
P1_30_B4
P1_20_B1
P1_40_B4
P1_30_B4
P1_20_B1
P1_20_B4
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P3_N1_B2
P3_N2_B2
P1_10_B1
P1_10_B2
P1_10_B3
P1_20_B1
P1_20_B2
P1_20_B3
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C2_B1
P2_C2_B2
P2_C2_B3
P2_C2_B4
P2_C3_B3
P2_C3_B4
P1_X3_B0
P1_50_B3
P1_50_B4
P2_C2_B0
P2_C3_B0
P1_30_B3
P1_20_B1
P1_20_B3
P1_20_B1
P1_20_B2
P1_20_B3
P1_20_B4
P1_30_B2
P1_30_B3
P1_40_B2
P1_30_B0
P1_20_B0
P1_00_B2
P1_X1_B0
P1_20_B2
P1_30_B3
P1_30_B3
P1_20_B4
P1_40_B1
P1_40_B4
P1_20_B0
P1_20_B2
P2_C2_B0
P1_30_B3
P1_10_B0
P1_20_B1
P1_40_B4
P1_30_B0
P1_20_B1
P1_20_B1
P1_30_B2
P1_30_B1
P1_30_B1
P1_20_B2
P1_30_B2
P1_10_B4
P1_10_B0
P1_20_B4
P1_40_B2
P1_10_B0
P1_10_B1
P1_10_B2
P1_10_B3
P1_10_B4
P1_20_B0
P1_20_B1
P1_20_B2
P1_20_B3
P1_20_B4
P1_30_B0
P1_30_B1
P1_30_B2
P1_30_B3
P1_30_B4
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_40_B0
P1_40_B1
P1_40_B3
P1_40_B4
P1_40_B0
P2_C2_B0
P2_C1_B0
P1_30_B0
P1_20_B2
P1_20_B1
P1_20_B1
P1_20_B1
P1_10_B1
P1_20_B4
P1_30_B4
P1_X4_B0
P2_C2_B0
P2_C3_B0
P2_C1_B0
P2_C3_B0
P1_20_B2
P1_X2_B0
P1_X3_B0
P1_30_B2
P1_20_B2
P3_N1_B2
P1_40_B2
P1_20_B2
P2_C1_B0
P1_20_B1
P1_20_B2
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_20_B1
P1_30_B2
P1_30_B2

P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B2
P1_10_B1
P1_30_B2
P2_C2_B0
P1_30_B2
P2_C2_B0
P2_C2_B3
P1_20_B2
P1_30_B2
P1_30_B2
P1_30_B3
P1_30_B4
P1_20_B0
P1_20_B0
P1_40_B0
P2_C2_B0
P2_C2_B0
P2_C3_B0
P1_20_B0
P1_30_B2
P1_20_B2
P1_10_B2
P1_50_B3
P1_50_B3
P3_N2_B2
P3_N2_B2
P3_N1_B2
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_20_B1
P1_20_B3
P1_20_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P2_C2_B0
P2_C2_B3
P1_20_B1
P1_30_B0
P1_X4_B0
P1_40_B0
P2_C2_B0
P1_40_B0
P1_20_B1
P1_20_B4
P1_20_B4
P1_20_B4
P1_X1_B0
P1_20_B0
P1_10_B1
P1_20_B1
P1_20_B1
P1_20_B0
P1_30_B4
P1_30_B2
P1_30_B2
P1_20_B1
P1_20_B1
P1_20_B1
P1_30_B1
P1_40_B0
P3_N3_B2
P1_20_B1
P3_N2_B2
P1_30_B0
P1_40_B2
P1_30_B0
P1_20_B4
P1_40_B4
P1_40_B3
P1_40_B4
P1_20_B0
P1_20_B3
P1_20_B4
P1_20_B0
P1_20_B0
P2_C3_B0
P2_C1_B0
P1_30_B2
P1_X1_B0
P1_20_B1
P1_20_B0
P1_40_B3
P1_20_B3
P1_20_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B1
P1_30_B2
P1_30_B3
P1_30_B4
P1_30_B2
P1_X3_B0
P1_X3_B0
P1_10_B2
P1_20_B2
P1_X4_B0
P1_10_B4
P2_C1_B0
P2_C2_B0
P1_30_B0
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_20_B3
P3_N3_B2
P1_20_B4
P1_20_B3
P1_20_B0
P1_30_B3
P1_30_B2
P1_30_B2
P1_30_B0
P1_30_B0
P1_30_B0
P1_30_B4
P1_30_B4
P1_00_B1
P1_20_B0
P1_30_B3
P1_40_B4
P2_C2_B0
P1_20_B3
P2_C3_B0
P2_C3_B0
P2_C2_B0
P1_00_B1
P1_00_B1
P1_X3_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B0
P1_30_B1
P2_C1_B0
P1_20_B1
P1_20_B3
P1_20_B4
P1_10_B1
P1_10_B3
P1_10_B4
P3_N3_B2
P1_30_B1
P2_C2_B0
P1_20_B4
P1_20_B4
P1_20_B4
P1_20_B4
P3_N1_B2
P3_N2_B2
P3_N3_B2
P1_X3_B0
P1_30_B2
P1_30_B2
P1_X2_B3
P1_X2_B4
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P2_C2_B0
P2_C3_B0
P2_C3_B0
P1_20_B1
P1_40_B0
P1_20_B0
P1_50_B4
P1_40_B3
P1_20_B1
P1_20_B2
P1_40_B2
P1_40_B3
P1_30_B1
P1_30_B2
P1_20_B4
P1_30_B1
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_40_B3
P1_10_B1
P1_10_B2
P1_30_B2
P1_30_B3
P1_30_B3
P1_30_B4
P1_10_B4
P1_20_B0
P3_N5_B5
P1_30_B0
P1_30_B0
P1_30_B2
P1_20_B1
P1_X2_B3
P1_X2_B4
P1_20_B2
P2_C3_B0
P1_10_B3
P2_C2_B0
P1_10_B0
P1_10_B2
P1_30_B2
P1_30_B4
P1_20_B3
P1_00_B1
P1_00_B1
P1_00_B1
P1_00_B1
P1_30_B2
P1_30_B3
P1_30_B0
P1_30_B0
P1_20_B4
P1_40_B0
P2_C2_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_40_B3
P1_30_B3
P1_20_B2
P3_N6_B5
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_50_B2
P2_C2_B0
P1_50_B0
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_50_B3
P1_50_B3
P1_50_B3
P1_30_B2
P2_C2_B0
P2_C2_B0
P1_30_B2
P1_30_B2
P3_N2_B2
P1_20_B3
P1_40_B3
P1_40_B4
P1_40_B3
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C2_B2
P2_C2_B3
P2_C3_B3
P2_C2_B4
P2_C3_B4
P1_X3_B0
P1_X5_B0
P3_N2_B2
P1_20_B1
P1_30_B0
P1_10_B1
P1_20_B2
P1_20_B2
P1_30_B2
P1_30_B2
P1_X5_B0
P1_X5_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_X5_B0
P1_20_B2
P2_C2_B0
P1_20_B1
P1_30_B0
P1_30_B2
P1_30_B2
P1_30_B3
P1_50_B3
P1_10_B0
P1_10_B3
P1_10_B3
P1_40_B3
P1_20_B1
P1_10_B2
P2_C1_B0
P1_X2_B0
P1_30_B2
P1_30_B0
P1_10_B3
P1_20_B0
P1_20_B3
P1_30_B3
P1_30_B3
P1_30_B0
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B1
P1_30_B4
P1_30_B4
P1_30_B4
P1_30_B4
P1_30_B4
P1_30_B4
P1_20_B2
P1_10_B4
P1_10_B4
P1_10_B4
P1_10_B4
P1_30_B3
P1_30_B4
P1_40_B0
P1_10_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_X1_B0
P1_30_B0
P1_30_B0
P1_30_B2
P2_C2_B0
P1_30_B2
P2_C2_B0
P1_20_B1
P1_20_B2
P1_20_B3
P1_20_B4
P1_30_B2
P1_30_B3
P2_C3_B0
P1_30_B0
P1_20_B3
P1_40_B3
P1_20_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_10_B0
P1_10_B3
P1_20_B0
P1_30_B0
P1_30_B3
P1_30_B2
P1_30_B2
P1_10_B2
P1_30_B2
P3_N2_B2
P1_30_B2
P1_30_B2
P1_20_B1
P1_20_B1
P1_20_B1
P1_30_B3
P1_10_B3
P1_30_B2
P1_20_B1
P1_20_B1
P1_20_B4
P1_20_B2
P1_30_B0
P1_30_B1
P1_30_B2
P1_30_B4
P1_40_B0
P1_20_B3
P1_20_B1
P1_20_B1
P1_20_B1
P1_10_B0
P1_20_B0
P1_30_B4
P1_C1_B0
P1_C2_B0
P1_C3_B0
P2_C2_B0
P2_C3_B0
P1_20_B1
P1_20_B0
P1_20_B1
P1_20_B3
P1_30_B2
P2_C2_B0
P1_40_B0
P1_30_B0
P2_C3_B0
P1_30_B2
P1_30_B3
P1_40_B0
P1_40_B3
P2_C2_B0
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_X5_B0
P2_C2_B0
P2_C3_B0
P1_30_B2
P1_10_B1
P1_20_B2
P1_20_B0
P1_10_B3
P2_C3_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_40_B3
P1_30_B3
P1_20_B1
P1_20_B4
P2_C2_B0
P1_10_B3
P1_20_B0
P1_X2_B0
P1_40_B4
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B4
P2_C2_B0
P2_C3_B0
P1_30_B1
P1_20_B4
P1_20_B3
P1_30_B0
P2_C2_B0
P2_C2_B0
P2_C2_B0
P2_C2_B0
P3_N4_B2
P1_30_B2
P1_30_B0
P1_20_B2
P1_20_B2
P1_30_B2
P1_20_B4
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B1
P1_20_B3
P1_10_B4
P1_10_B4
P1_30_B2
P1_20_B1
P1_20_B3
P2_C2_B0
P1_X5_B0
P1_X5_B0
P1_X5_B0
P1_10_B4
P1_20_B4
P2_C2_B0
P2_C3_B0
P1_30_B2
P1_40_B2
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P1_30_B1
P2_C3_B0
P1_30_B0
P2_C3_B0
P1_40_B0
P1_20_B4
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_40_B0
P2_C2_B3
P1_40_B0
P1_20_B3
P1_20_B4
P1_40_B4
P1_10_B3
P1_40_B3
P1_20_B4
P1_30_B0
P1_30_B3
P2_CN_B0
P1_30_B3
P1_30_B0
P1_30_B2
P1_30_B3
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_50_B2
P1_30_B1
P1_10_B1
P1_30_B1
P1_30_B2
P1_20_B4
P1_10_B1
P1_40_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_10_B1
P1_50_B4
P1_20_B1
P1_20_B2
P2_C3_B0
P1_20_B1
P1_30_B2
P1_20_B4
P1_20_B0
P1_10_B4
P1_30_B2
P1_20_B2
P1_30_B3
P1_20_B3
P2_C3_B0
P1_50_B2
P2_C2_B0
P1_20_B1
P1_30_B4
P2_C2_B0
P2_C3_B0
P1_30_B0
P2_C2_B0
P2_C3_B0
P1_30_B0
P1_20_B2
P1_30_B2
P1_10_B2
P1_40_B2
P1_10_B3
P1_20_B0
P2_C1_B0
P2_C1_B0
P2_C1_B0
P2_C3_B0
P1_20_B3
P1_X5_B0
P1_X5_B0
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_20_B1
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_10_B4
P1_30_B2
P1_30_B2
P2_C2_B0
P1_X5_B0
P1_40_B1
P1_50_B1
P1_30_B3
P1_30_B3
P1_40_B3
P1_30_B3
P1_30_B2
P1_30_B2
P1_20_B1
P1_30_B2
P1_30_B2
P2_C2_B0
P1_20_B0
P1_40_B2
P1_40_B2
P1_40_B2
P1_40_B2
P1_30_B3
P1_10_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_30_B4
P1_20_B3
P1_30_B3
P1_40_B2
P2_C2_B0
P1_30_B3
P1_10_B3
P1_50_B0
P2_C2_B0
P1_20_B2
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C2_B0
P1_30_B2
P1_20_B1
P2_C2_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B0
P1_20_B0
P1_20_B1
P1_20_B1
P1_10_B4
P1_10_B4
P1_10_B4
P1_10_B4
P1_10_B4
P1_30_B3
P1_30_B1
P1_30_B0
P1_20_B1
P1_10_B4
P1_20_B2
P1_20_B1
P2_C2_B0
P1_30_B0
P1_30_B2
P1_30_B1
P1_30_B2
P1_30_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B2
P1_40_B1
P1_40_B3
P1_20_B3
P1_30_B2
P1_20_B3
P1_40_B3
P1_30_B1
P2_C2_B0
P2_C3_B0
P1_50_B4
P1_20_B1
P1_30_B1
P1_30_B0
P1_30_B0
P1_20_B0
P1_20_B0
P1_20_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_X5_B0
P1_X5_B0
P1_40_B0
P1_50_B0
P1_50_B1
P1_50_B2
P1_50_B3
P1_10_B4
P1_20_B4
P1_30_B0
P2_C2_B0
P1_20_B2
P1_40_B2
P2_C3_B3
P1_50_B4
P1_40_B3
P2_C2_B0
P2_C2_B0
P2_C2_B0
P1_10_B3
P1_30_B0
P1_30_B3
P1_30_B4
P1_20_B2
P2_C2_B0
P1_20_B2
P1_C2_B0
P1_10_B3
P2_C2_B0
P2_C3_B0
P1_40_B2
P1_10_B0
P1_10_B1
P2_C2_B0
P2_C2_B0
P1_20_B3
P1_20_B4
P1_40_B2
P1_30_B0
P1_40_B3
P1_30_B2
P1_30_B3
P1_50_B2
P1_50_B3
P1_30_B0
P3_N7_B5
P3_N8_B5
P3_N9_B5
P3_N10_B5
P3_N11_B5
P1_30_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B1
P1_30_B1
P1_30_B3
P1_20_B4
P1_20_B2
P1_30_B2
P2_C2_B0
P1_20_B3
P1_30_B0
P2_C2_B0
P1_40_B3
P1_20_B3
P1_20_B2
P1_30_B2
P1_20_B2
P1_20_B0
P1_30_B2
P1_20_B1
P1_20_B2
P1_20_B3
P1_20_B4
P1_30_B0
P1_30_B2
P1_20_B0
P2_C2_B0
P1_30_B2
P1_40_B2
P2_C3_B0
P1_20_B0
P1_40_B0
P2_C2_B0
P2_C3_B3
P1_30_B1
P1_30_B4
P1_30_B2
P1_30_B2
P1_20_B1
P1_20_B2
P1_X5_B0
P1_30_B0
P1_20_B3
P1_40_B3
P1_40_B4
P1_20_B0
P1_30_B2
P1_20_B1
P1_X2_B0
P1_30_B3
P1_40_B3
P1_20_B1
P1_20_B1
P1_20_B1
P1_20_B0
P2_C3_B3
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_10_B1
P1_30_B2
P2_C3_B0
P2_C3_B0
P1_20_B3
P1_30_B2
P1_30_B4
P1_20_B3
P1_X5_B0
P1_X5_B0
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_30_B2
P1_10_B1
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_20_B1
P1_30_B0
P2_C2_B0
P2_C1_B0
P2_C3_B0
P1_20_B4
P2_C2_B0
P1_40_B0
P1_30_B2
P1_30_B0
P1_20_B1
P1_20_B2
P1_30_B2
P1_40_B2
P1_40_B2
P1_30_B4
P1_10_B1
P2_C2_B0
P1_30_B2
P1_40_B2
P1_30_B4
P1_20_B1
P1_30_B2
P1_30_B2
P1_20_B0
P1_30_B1
P1_X5_B0
P1_30_B2
P1_10_B2
P1_X1_B0
P2_C3_B0
P1_30_B0
P1_20_B1
P1_20_B3
P1_20_B4
P1_X2_B0
P1_X2_B0
P1_X2_B0
P1_X2_B0
P1_X2_B0
P1_30_B2
P2_C2_B0
P2_C2_B0
P1_40_B2
P1_40_B1
P1_20_B3
P1_30_B1
P1_30_B0
P1_40_B2
P1_40_B3
P1_X2_B0
P1_30_B2
P1_20_B1
P1_30_B2
P1_10_B1
P2_C3_B0
P1_30_B2
P1_30_B0
P1_30_B2
P1_30_B4
P1_40_B1
P1_20_B1
P2_C2_B0
P2_C1_B0
P2_C2_B0
P1_50_B0
P1_30_B2
P1_30_B2
P1_20_B2
P1_10_B2
P1_30_B2
P2_C1_B0
P2_C3_B0
P1_20_B4
P2_C3_B0
P2_C2_B0
P2_C1_B0
P1_30_B1
P1_20_B3
P1_20_B2
P2_C2_B0
P3_N1_B2
P1_X2_B0
P1_X4_B0
P1_30_B2
P1_20_B3
P1_20_B3
P1_20_B2
P1_50_B0
P1_30_B4
P1_30_B2
P1_20_B0
P2_C2_B0
P2_C3_B0
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C1_B0
P2_C2_B0
P2_C3_B0
P1_30_B2
P1_X5_B0
P1_30_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_50_B2
P1_30_B3
P1_40_B0
P1_30_B3
P1_30_B1
P1_20_B4
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P2_C2_B0
P1_10_B1
P2_C3_B0
P1_30_B3
P2_C2_B0
P2_C1_B0
P2_C2_B0
P2_C3_B0
P2_C2_B0
P2_C3_B0
P2_C2_B0
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B4
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_30_B3
P1_10_B1
P2_C2_B0
P2_C2_B0
P2_C1_B0
P2_C3_B0
P1_40_B4
P1_40_B0
P1_20_B1
P1_20_B3
P1_20_B2
P2_C2_B0
P2_C3_B0
P1_20_B4
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B2
P1_30_B0
P1_30_B0
P1_30_B2
P1_30_B1

In [30]:
customer_df['nozzle'] = version
customer_df

,customer,customer_id,xdc,product_family,size_new,size,coating_new,coating,amount,fitting,date_order,date_delivery_ought,date_delivery_is,delivery_comment,general_comment,division_tag,machine,machine_type,training_kits,channels,delivery_time,locality_country,locality_city,replacement_delivery,replacement_for_id,date_order_month,date_delivery_month,date_order_year,date_delivery_year,finished,nozzle
0,ADC,2,PDC,P1,30,80,B2,T2,18.0,S3,2018-11-30,2019-02-15,2021-03-05,Part 1,Teil 1 zusammen mit 12x OEM's + 24 Dummy Sets...,NaN,1.0,M0,NaN,NaN,826.0,UK,Witney,NaN,NaN,2018-11,2021-03,2018.0,2021.0,1,P1_30_B2
1,ADC,2,PDC,P1,30,80,B2,T2,18.0,S3,2018-11-30,NaN,2021-03-15,Part 2,Teil 2 zusammen mit 12x OEM's + 24 Dummy Sets...,NaN,1.0,M0,NaN,NaN,836.0,UK,Witney,NaN,NaN,2018-11,2021-03,2018.0,2021.0,1,P1_30_B2
2,Optolane Technologies Inc,194,PDC,P1,40,90,B1,T1,10.0,S5/S11,2019-03-19,NaN,2020-01-31,Dez.,zusammen mit S100-Rocket I Portal Upgrade (10...,NaN,1.0,M4,NaN,10,318.0,South Korea,Seongnam-si (Gyeonggi-do),NaN,NaN,2019-03,2020-01,2019.0,2020.0,1,P1_40_B1
3,MDC BIMSB,162,PDC-C,P2,C1,CS,B0,T0,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,none,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1,P2_C1_B0
4,MDC BIMSB,162,PDC-C,P2,C2,CM,B0,T0,4.0,S5/S11,2019-04-26,2020-02-25,2020-02-26,NaN,NaN,Berliner Institut für Medizinische System Biol...,NaN,none,NaN,NaN,306.0,Germany,Berlin,NaN,NaN,2019-04,2020-02,2019.0,2020.0,1,P2_C2_B0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2782,ADC,2,PDC,P1,30,80,B2,T2,35.0,S3,2022-06-01,2022-06-01,NaN,NaN,June22 Call Off,NaN,NaN,none,NaN,NaN,NaN,Ireland,Donegal,NaN,NaN,2022-06,NaN,2022.0,NaN,0,P1_30_B2
2783,Randox Teoranta,220,PDC,P1,30,80,B0,T0,10.0,S5/S11,2022-07-13,2022-10-05,NaN,NaN,NaN,NaN,NaN,none,NaN,NaN,NaN,Ireland,Dungloe,NaN,NaN,2022-07,NaN,2022.0,NaN,0,P1_30_B0
2784,MPI KGF,165,PDC,P1,30,80,B0,T0,3.0,S5/S11,2021-09-02,2022-11-25,NaN,NaN,NaN,Institut für Kolloid -und Grenzflaechenforschung,NaN,none,NaN,NaN,NaN,Germany,Potsdam-Golm,NaN,NaN,2021-09,NaN,2021.0,NaN,0,P1_30_B0
2785,Fred Hutchinson Cancer Center,95,PDC,P1,30,80,B2,T2,3.0,S5/S11,2022-09-02,NaN,NaN,NaN,NaN,NaN,1.0,M1,NaN,2,NaN,USA,Seattle,NaN,NaN,2022-09,NaN,2022.0,NaN,0,P1_30_B2
2786,Scienion Inc,237,PDC,P1,30,80,B1,T1,2.0,S5/S11,2022-09-02,NaN,NaN,NaN,NaN,NaN,1.0,M1,NaN,2,NaN,USA,Tempe,NaN,NaN,2022-09,NaN,2022.0,NaN,0,P1_30_B1

In [31]:
customer_df['nozzle'].unique()

array(['P1_30_B2', 'P1_40_B1', 'P2_C1_B0', 'P2_C2_B0', 'P2_C3_B0',
       'P1_00_B1', 'P1_00_B2', 'P1_40_B2', 'P1_40_B4', 'P1_40_B0',
       'P1_30_B3', 'P1_20_B0', 'P1_00_B3', 'P1_10_B0', 'P1_30_B0',
       'P1_00_B4', 'P1_20_B1', 'P1_10_B1', 'P1_00_B0', 'P1_10_B4',
       'P1_20_B3', 'P1_20_B2', 'P1_50_B1', 'P1_50_B2', 'P1_50_B3',
       'P1_50_B4', 'P1_30_B1', 'P1_20_B4', 'P1_40_B3', 'P1_30_B4',
       'P1_X1_B0', 'P1_10_B2', 'P1_10_B3', 'P2_C2_B2', 'P2_C2_B4',
       'P2_C2_B3', 'P1_X4_B0', 'P1_50_B0', 'P3_N1_B2', 'P3_N2_B2',
       'P3_N3_B2', 'P2_C3_B4', 'P2_C3_B3', 'P1_X2_B0', 'P1_X3_B0',
       'P1_X5_B0', 'P2_C2_B1', 'P1_X2_B3', 'P1_X2_B4', 'P3_N5_B5',
       'P3_N6_B5', 'P1_C1_B0', 'P1_C2_B0', 'P1_C3_B0', 'P3_N4_B2',
       'P2_CN_B0', 'P3_N7_B5', 'P3_N8_B5', 'P3_N9_B5', 'P3_N10_B5',
       'P3_N11_B5'], dtype=object)

## Create a New Dataset for Anonymised Data

This Data set will be our final Data Set to use on Tableau visualization.

In [32]:
anon_df = customer_df[[
    "customer_id", "product_family", "size_new", "coating_new", "nozzle", "amount", "date_order", "date_delivery_is", "delivery_time", "machine_type",
    "locality_country", "locality_city", "replacement_delivery"]]
anon_df

,customer_id,product_family,size_new,coating_new,nozzle,amount,date_order,date_delivery_is,delivery_time,machine_type,locality_country,locality_city,replacement_delivery
0,2,P1,30,B2,P1_30_B2,18.0,2018-11-30,2021-03-05,826.0,M0,UK,Witney,NaN
1,2,P1,30,B2,P1_30_B2,18.0,2018-11-30,2021-03-15,836.0,M0,UK,Witney,NaN
2,194,P1,40,B1,P1_40_B1,10.0,2019-03-19,2020-01-31,318.0,M4,South Korea,Seongnam-si (Gyeonggi-do),NaN
3,162,P2,C1,B0,P2_C1_B0,4.0,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,NaN
4,162,P2,C2,B0,P2_C2_B0,4.0,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2782,2,P1,30,B2,P1_30_B2,35.0,2022-06-01,NaN,NaN,none,Ireland,Donegal,NaN
2783,220,P1,30,B0,P1_30_B0,10.0,2022-07-13,NaN,NaN,none,Ireland,Dungloe,NaN
2784,165,P1,30,B0,P1_30_B0,3.0,2021-09-02,NaN,NaN,none,Germany,Potsdam-Golm,NaN
2785,95,P1,30,B2,P1_30_B2,3.0,2022-09-02,NaN,NaN,M1,USA,Seattle,NaN
2786,237,P1,30,B1,P1_30_B1,2.0,2022-09-02,NaN,NaN,M1,USA,Tempe,NaN

## Replace NaN Values and Fix the Misspellings

After finally deciding our final data set now we can take care of nan values so when we use Tableau we won't have problems.

In [33]:
anon_df['replacement_delivery'] = anon_df['replacement_delivery'].fillna(0)
anon_df['replacement_delivery']

/var/folders/c3/pkgzz_891b148813l5gzlgl40000gn/T/ipykernel_68606/4134864090.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anon_df['replacement_delivery'] = anon_df['replacement_delivery'].fillna(0)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
2782    0.0
2783    0.0
2784    0.0
2785    0.0
2786    0.0
Name: replacement_delivery, Length: 2787, dtype: float64

In [34]:
anon_df['replacement_delivery'].unique()

array([0., 1.])

In [35]:
#Find the nan value in the Date_Order column
anon_df['date_order'].unique()

array(['2018-11-30', '2019-03-19', '2019-04-26', '2019-06-03',
       '2019-07-26', '2019-08-02', '2019-09-01', '2019-09-04',
       '2019-09-16', '2019-09-13', '2019-09-18', '2019-10-01',
       '2019-10-07', '2019-10-08', '2019-10-15', '2019-10-17',
       '2019-10-21', '2019-10-24', '2019-10-31', '2019-11-01',
       '2019-11-04', '2019-11-05', '2019-11-06', '2019-11-13',
       '2019-11-14', '2019-11-15', '2019-11-18', '2019-11-19',
       '2019-11-20', '2019-11-26', '2019-11-28', '2019-11-29',
       '2019-12-03', '2019-12-04', '2019-12-05', '2019-12-09',
       '2019-12-12', '2019-12-13', '2019-12-16', '2019-12-17',
       '2019-12-18', '2019-12-01', '2019-12-19', '2019-12-20',
       '2019-12-23', '2020-01-01', '2020-01-02', '2020-01-03',
       '2020-01-06', '2020-01-07', '2020-01-08', '2020-01-14',
       '2020-03-19', '2020-01-15', '2020-01-16', '2020-01-05',
       '2020-01-17', '2020-01-20', '2020-01-21', '2020-02-20',
       '2020-01-23', '2020-01-27', '2020-01-28', '2020-01-29',
       '2020-01-30', '2020-01-31', '2020-02-04', '2020-02-01',
       '2020-02-05', '2020-02-06', '2020-02-07', '2020-02-10',
       '2020-02-11', '2020-02-14', '2020-02-13', '2020-02-17',
       '2020-02-18', '2020-02-19', '2020-02-25', '2020-02-24',
       '2020-02-26', '2020-02-27', '2020-02-28', '2020-03-02',
       '2020-03-01', '2020-03-06', '2020-03-09', '2020-03-10',
       '2020-03-12', '2020-03-16', '2020-03-18', '2020-03-20',
       '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26',
       '2020-03-27', '2020-03-31', '2020-04-01', '2020-04-03',
       '2020-04-08', '2020-04-09', '2020-04-16', '2020-04-15',
       '2020-05-26', '2020-04-17', '2020-04-20', '2020-04-22',
       '2020-04-23', '2020-04-27', '2020-04-29', '2020-05-04',
       '2020-05-05', '2020-05-06', '2020-05-01', '2020-05-11',
       '2020-05-13', '2020-07-18', '2020-05-14', '2020-05-18',
       '2020-05-22', '2020-05-25', '2020-11-04', '2020-05-27',
       '2020-05-28', '2020-06-01', '2020-06-02', '2020-06-03',
       '2020-06-04', '2020-06-05', '2020-06-11', '2020-06-15',
       '2020-06-16', '2020-06-18', '2020-06-19', '2020-06-22',
       '2020-06-25', '2020-06-30', '2020-06-21', '2020-07-01',
       '2020-07-02', '2020-07-03', '2020-07-08', '2020-07-09',
       '2020-07-15', '2020-07-16', '2020-07-17', '2020-07-20',
       '2020-07-21', '2020-07-23', '2020-07-24', '2020-07-28',
       '2020-07-29', '2020-07-31', '2020-08-01', '2020-08-03',
       '2020-08-05', '2020-08-06', '2020-08-07', '2020-08-10',
       '2020-08-12', '2020-08-13', '2020-08-19', '2019-12-10',
       '2020-09-01', '2020-10-01', '2020-11-01', '2020-12-01',
       '2021-01-01', '2020-08-20', '2020-08-24', '2020-08-26',
       '2020-08-28', '2020-08-08', '2020-09-02', '2020-08-27',
       '2020-08-31', '2020-09-04', '2020-09-07', '2020-09-08',
       '2020-09-09', '2020-09-14', '2020-09-15', '2020-09-16',
       '2020-09-17', '2020-09-18', '2020-09-21', '2020-09-23',
       '2020-09-24', '2020-09-25', '2020-09-28', '2020-09-29',
       '2020-09-30', '2021-02-01', '2020-10-06', '2020-10-05',
       '2020-10-07', '2020-10-09', '2020-10-12', '2020-10-14',
       '2020-10-13', '2020-10-16', '2020-10-20', '2020-10-15',
       '2020-10-21', '2020-10-19', '2020-10-27', '2020-10-30',
       '2020-10-26', '2020-10-28', '2020-11-02', '2020-10-29',
       '2020-11-03', '2020-11-05', '2020-11-06', '2020-11-09',
       '2020-11-10', '2020-10-23', '2020-11-12', '2020-11-11',
       '2020-11-13', '2020-11-17', '2020-11-18', '2020-11-19',
       '2020-11-23', '2020-11-16', '2020-11-24', '2020-11-25',
       '2020-11-27', '2020-11-26', '2020-12-02', '2020-12-03',
       '2020-12-04', '2020-12-07', '2020-12-08', '2020-12-10',
       '2020-12-11', '2021-09-22', '2020-12-12', '2020-12-14',
       '2020-12-15', '2020-12-16', '2020-12-17', '2020-12-18',
       '2020-12-13', '2020-12-28', '2020-12-30', '2021-01-05',
       '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-11',
       '2020-12-22', '2021-01-12', '2021-03-01', '2021-04-01',
       '2021-05-01', '2021-06-01', '2021-07-01', '2021-09-01',
       '2021-11-01', '2021-12-01', '2021-01-15', '2021-01-19',
       '2021-01-20', '2021-01-22', '2021-01-16', '2021-01-14',
       '2021-01-18', '2021-01-25', '2021-01-26', '2021-01-29',
       '2021-02-02', '2021-02-03', '2021-01-28', '2021-02-05',
       '2021-02-04', '2021-02-08', '2021-08-01', '2021-10-01',
       '2022-01-01', '2022-02-01', '2021-02-09', '2021-02-11',
       '2021-02-12', '2021-02-10', '2021-02-15', '2021-02-16',
       '2021-02-18', '2021-02-19', '2021-02-23', '2021-02-21',
       '2021-02-22', '2021-02-24', '2021-02-25', '2021-03-02',
       '2021-03-03', '2021-03-04', '2021-03-08', '2021-03-05',
       '2021-03-09', '2021-03-11', '2021-03-10', '2021-03-16',
       '2021-03-17', '2021-03-18', '2021-03-22', '2021-03-23',
       '2021-03-24', '2021-03-25', '2021-03-26', '2021-03-12',
       '2021-03-19', '2021-03-30', '2021-04-05', '2021-04-06',
       '2021-04-07', '2021-04-09', '2021-09-02', '2021-08-04',
       '2021-04-13', '2021-04-14', '2021-04-12', '2021-04-15',
       '2021-04-19', '2021-04-21', '2021-04-22', '2021-04-24',
       '2021-04-27', '2021-04-26', '2021-04-28', '2021-04-29',
       '2021-05-05', '2021-05-06', '2021-04-30', '2021-05-07',
       '2021-05-10', '2021-05-13', '2021-05-12', '2021-05-14',
       '2021-05-17', '2021-05-18', '2021-05-19', '2021-05-20',
       '2021-05-21', '2021-05-26', '2021-05-25', '2021-05-27',
       '2021-05-28', '2021-05-24', '2021-06-02', '2021-06-03',
       '2021-06-04', '2021-06-07', '2021-06-08', '2021-06-09',
       '2021-06-10', '2021-06-11', '2021-06-15', '2021-06-14',
       '2021-06-16', '2021-06-18', '2021-06-17', '2021-06-22',
       '2021-06-23', '2021-03-15', '2021-06-24', '2021-06-21',
       '2021-06-25', '2021-06-26', '2021-06-28', '2021-06-29',
       '2021-07-02', '2021-07-07', '2021-07-05', '2021-07-06',
       '2021-07-08', '2021-07-13', '2021-07-15', '2021-07-14',
       '2021-07-21', '2021-07-16', '2021-07-19', '2021-07-23',
       '2021-08-03', '2021-07-25', '2021-07-26', '2021-07-09',
       '2021-07-20', '2021-07-28', '2021-07-29', '2021-07-27',
       '2021-07-30', '2021-08-02', '2021-08-05', '2021-08-06',
       '2021-08-09', '2022-03-01', '2022-04-01', '2022-05-01',
       '2022-06-01', '2022-07-01', '2022-08-01', '2021-08-11',
       '2021-08-12', '2021-08-13', '2021-08-18', '2021-08-20',
       '2021-08-16', '2021-08-10', '2021-08-27', '2021-08-19',
       '2021-08-23', '2021-08-25', '2021-08-26', '2021-08-31',
       '2021-09-03', '2021-09-06', '2021-09-07', '2021-09-09',
       '2021-09-08', '2021-09-10', '2021-09-13', '2021-09-14',
       '2021-09-16', '2021-09-20', '2021-09-24', '2021-09-25',
       '2021-09-27', '2021-09-30', '2021-09-28', '2021-09-29',
       '2021-10-08', '2021-10-04', '2021-10-05', '2021-09-23',
       '2021-10-07', '2021-10-06', '2021-10-13', '2021-10-15',
       '2021-10-18', '2021-10-19', '2021-10-21', '2021-03-29',
       '2021-10-20', '2021-10-25', '2021-10-22', '2021-10-28',
       '2021-10-29', '2021-10-24', '2021-10-26', '2021-10-12',
       '2021-11-04', '2021-11-03', '2021-11-05', '2021-11-08',
       '2021-11-16', '2021-11-15', '2021-11-18', '2021-11-19',
       '2021-11-21', '2021-11-22', '2021-11-17', '2021-11-23',
       '2021-11-29', '2021-11-25', '2021-11-26', '2021-12-06',
       '2021-12-07', '2021-12-02', '2021-12-03', '2021-12-09',
       '2021-11-30', '2021-12-08', '2021-12-10', '2021-12-13',
       '2021-12-14', '2021-12-15', '2021-12-16', '2021-12-20',
       '2021-12-17', '2022-09-01', '2022-10-01', '2022-11-01',
       '2022-12-01', '2021-12-21', '2021-12-23', '2022-01-03',
       '2021-12-24', '2022-01-04', '2021-12-18', '2022-01-05',
       '2022-01-10', '2021-10-30', '2022-01-12', '2022-01-13',
       '2022-01-11', '2022-01-17', '2022-01-18', '2022-01-19',
       '2022-01-14', '2022-01-21', '2022-01-26', '2022-01-27',
       '2022-01-31', '2022-01-28', '2022-02-03', '2022-02-04',
       '2022-02-08', '2022-02-09', '2022-02-11', '2022-02-14',
       '2022-02-10', '2022-02-16', '2022-02-15', '2023-01-01',
       '2023-02-01', '2023-03-01', '2022-02-17', '2022-02-21',
       '2022-02-18', '2022-02-23', '2022-02-24', '2022-02-28',
       '2022-03-07', '2022-03-09', '2022-03-03', '2022-03-17',
       '2022-03-21', '2022-03-04', '2022-03-02', '2022-03-08',
       '2022-03-10', '2022-03-14', '2022-03-11', '2022-03-15',
       '2022-03-16', '2022-03-18', '2022-03-22', '2022-03-20',
       '2022-03-23', '2022-03-25', '2022-03-28', '2022-03-29',
       '2022-04-05', '2022-04-06', '2022-04-07', '2023-04-01',
       '2022-03-31', '2022-04-13', '2022-04-14', '2022-04-12',
       '2022-04-20', '2022-04-26', '2022-02-27', '2022-04-25',
       '2022-04-28', '2022-04-23', '2022-04-27', '2022-05-03',
       '2022-05-05', '2022-05-04', '2022-04-29', '2022-05-02',
       '2022-05-06', '2022-05-12', '2022-05-11', '2022-05-10',
       '2022-05-09', '2022-05-13', '2022-05-16', '2022-05-17',
       '2022-05-18', '2022-05-19', '2022-04-30', '2022-05-20',
       '2022-05-23', '2022-04-08', '2022-05-24', '2022-05-31',
       '2022-05-27', '2022-06-02', '2022-06-07', '2022-06-03',
       '2022-06-09', '2022-06-13', '2022-06-10', '2022-06-16',
       '2022-06-14', '2022-06-20', '2022-06-21', '2022-06-22',
       '2022-06-23', '2022-06-24', '2022-06-27', '2022-06-28',
       '2022-06-30', '2022-07-04', '2022-07-06', '2022-07-05',
       '2022-07-07', '2022-07-14', '2022-07-08', '2022-07-13',
       '2022-07-12', '2022-07-15', '2022-07-18', '2022-07-21',
       '2022-07-20', '2022-07-25', '2022-08-02', '2022-08-03', nan,
       '2022-08-04', '2022-07-29', '2022-07-28', '2022-08-05',
       '2022-08-08', '2022-08-09', '2022-08-10', '2022-06-29',
       '2022-08-11', '2022-08-12', '2022-08-15', '2022-07-19',
       '2022-08-17', '2022-08-18', '2022-08-22', '2022-07-26',
       '2022-08-30', '2022-08-29', '2022-08-26', '2022-08-25',
       '2022-09-02'], dtype=object)

In [36]:
#Find the nan value in date_order column
anon_df[anon_df['date_order'].isna()]

,customer_id,product_family,size_new,coating_new,nozzle,amount,date_order,date_delivery_is,delivery_time,machine_type,locality_country,locality_city,replacement_delivery
2707,213,P3,N1,B2,P3_N1_B2,10.0,NaN,NaN,NaN,none,USA,San Diego,0.0

In [37]:
#Drop the row which has the order date as a nan value
anon_df = anon_df.drop(anon_df.index[2707])
anon_df

,customer_id,product_family,size_new,coating_new,nozzle,amount,date_order,date_delivery_is,delivery_time,machine_type,locality_country,locality_city,replacement_delivery
0,2,P1,30,B2,P1_30_B2,18.0,2018-11-30,2021-03-05,826.0,M0,UK,Witney,0.0
1,2,P1,30,B2,P1_30_B2,18.0,2018-11-30,2021-03-15,836.0,M0,UK,Witney,0.0
2,194,P1,40,B1,P1_40_B1,10.0,2019-03-19,2020-01-31,318.0,M4,South Korea,Seongnam-si (Gyeonggi-do),0.0
3,162,P2,C1,B0,P2_C1_B0,4.0,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0
4,162,P2,C2,B0,P2_C2_B0,4.0,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2782,2,P1,30,B2,P1_30_B2,35.0,2022-06-01,NaN,NaN,none,Ireland,Donegal,0.0
2783,220,P1,30,B0,P1_30_B0,10.0,2022-07-13,NaN,NaN,none,Ireland,Dungloe,0.0
2784,165,P1,30,B0,P1_30_B0,3.0,2021-09-02,NaN,NaN,none,Germany,Potsdam-Golm,0.0
2785,95,P1,30,B2,P1_30_B2,3.0,2022-09-02,NaN,NaN,M1,USA,Seattle,0.0
2786,237,P1,30,B1,P1_30_B1,2.0,2022-09-02,NaN,NaN,M1,USA,Tempe,0.0

In [38]:
#Check the nan values in delivery_time
anon_df['delivery_time'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
2782     True
2783     True
2784     True
2785     True
2786     True
Name: delivery_time, Length: 2786, dtype: bool

In [39]:
#fill the non values with 9999 later we'll set a limit when we plot it
anon_df['delivery_time'].fillna(9999, inplace =True)

Here in the locality_country column we had some countries which written couple of times in different names and some countries had misspellings so we fixed those issues.

In [40]:
#Check the country names if there's any misspelling
anon_df['locality_country'].unique()

array(['UK', 'South Korea', 'Germany', 'USA', 'Netherlands', 'China',
       'France', 'Ireland', 'Spain', 'Australia', 'Czech Republic',
       'Sweden', 'Singapur', 'Canada', 'Belgium', 'Portugal', 'Denmark',
       'Finnland', 'Japan', 'Poland', 'Austria', 'Italy', 'Lithuania',
       'Switzerland', 'Russia', 'Turkey', 'Israel', 'Thailand',
       'Slovakia', 'Taiwan', 'Luxemburg'], dtype=object)

In [41]:
#Correct the country names
customer_df['locality_country'] = customer_df['locality_country'].replace(['S5/S11', 'England', 'Scottland', 'United Kingdom', 'Isreal'],['USA', 'UK', 'UK', 'UK', 'Israel'])
customer_df['locality_country'].unique()

array(['UK', 'South Korea', 'Germany', 'USA', 'Netherlands', 'China',
       'France', 'Ireland', 'Spain', 'Australia', 'Czech Republic',
       'Sweden', 'Singapur', 'Canada', 'Belgium', 'Portugal', 'Denmark',
       'Finnland', 'Japan', 'Poland', 'Austria', 'Italy', 'Lithuania',
       'Switzerland', 'Russia', 'Turkey', 'Israel', 'Thailand',
       'Slovakia', 'Taiwan', 'Luxemburg'], dtype=object)

## Create New Columns for the Price of the Product and Revenue

Here first we assigned approximet prices for each product and made a dictionary to assign our products.

In [42]:
#keys of the product list
version_keys = list(anon_df['nozzle'].unique())
version_keys

['P1_30_B2',
 'P1_40_B1',
 'P2_C1_B0',
 'P2_C2_B0',
 'P2_C3_B0',
 'P1_00_B1',
 'P1_00_B2',
 'P1_40_B2',
 'P1_40_B4',
 'P1_40_B0',
 'P1_30_B3',
 'P1_20_B0',
 'P1_00_B3',
 'P1_10_B0',
 'P1_30_B0',
 'P1_00_B4',
 'P1_20_B1',
 'P1_10_B1',
 'P1_00_B0',
 'P1_10_B4',
 'P1_20_B3',
 'P1_20_B2',
 'P1_50_B1',
 'P1_50_B2',
 'P1_50_B3',
 'P1_50_B4',
 'P1_30_B1',
 'P1_20_B4',
 'P1_40_B3',
 'P1_30_B4',
 'P1_X1_B0',
 'P1_10_B2',
 'P1_10_B3',
 'P2_C2_B2',
 'P2_C2_B4',
 'P2_C2_B3',
 'P1_X4_B0',
 'P1_50_B0',
 'P3_N1_B2',
 'P3_N2_B2',
 'P3_N3_B2',
 'P2_C3_B4',
 'P2_C3_B3',
 'P1_X2_B0',
 'P1_X3_B0',
 'P1_X5_B0',
 'P2_C2_B1',
 'P1_X2_B3',
 'P1_X2_B4',
 'P3_N5_B5',
 'P3_N6_B5',
 'P1_C1_B0',
 'P1_C2_B0',
 'P1_C3_B0',
 'P3_N4_B2',
 'P2_CN_B0',
 'P3_N7_B5',
 'P3_N8_B5',
 'P3_N9_B5',
 'P3_N10_B5',
 'P3_N11_B5']

In [43]:
#Values of the price dict
price_values = list([750, 
           750, 
           700, 
           700, 
           700, 
           900, 
           900, 
           750, 
           800, 
           750, 
           750, 
           750, 
           850, 
           750, 
           750, 
           1000, 
           750, 
           750, 
           750, 
           850, 
           750, 
           750, 
           750,
           750,
           750,
           800,
           750,
           800,
           750,
           800,
           50,
           750,
           750,
           700,
           700,
           700,
           50,
           750,
           700,
           700,
           700, 
           750,
           750,
           50,
           50,
           50,
           750,
           50,
           50,
           700,
           700,
           600,
           600,
           600,
           700,
           600,
           700,
           700,
           700,
           700,
           700])
price_values

[750,
 750,
 700,
 700,
 700,
 900,
 900,
 750,
 800,
 750,
 750,
 750,
 850,
 750,
 750,
 1000,
 750,
 750,
 750,
 850,
 750,
 750,
 750,
 750,
 750,
 800,
 750,
 800,
 750,
 800,
 50,
 750,
 750,
 700,
 700,
 700,
 50,
 750,
 700,
 700,
 700,
 750,
 750,
 50,
 50,
 50,
 750,
 50,
 50,
 700,
 700,
 600,
 600,
 600,
 700,
 600,
 700,
 700,
 700,
 700,
 700]

In [44]:
# create dictionary for the prices of each product
def price_dictionary(version_keys, price_values):
    result = {} # empty dictionary
    for key, value in zip(version_keys, price_values):
        result[key] = value
    return result

print(price_dictionary(version_keys=version_keys, price_values=price_values))

price_dict= price_dictionary(version_keys=version_keys, price_values=price_values)
price_dict

{'P1_30_B2': 750, 'P1_40_B1': 750, 'P2_C1_B0': 700, 'P2_C2_B0': 700, 'P2_C3_B0': 700, 'P1_00_B1': 900, 'P1_00_B2': 900, 'P1_40_B2': 750, 'P1_40_B4': 800, 'P1_40_B0': 750, 'P1_30_B3': 750, 'P1_20_B0': 750, 'P1_00_B3': 850, 'P1_10_B0': 750, 'P1_30_B0': 750, 'P1_00_B4': 1000, 'P1_20_B1': 750, 'P1_10_B1': 750, 'P1_00_B0': 750, 'P1_10_B4': 850, 'P1_20_B3': 750, 'P1_20_B2': 750, 'P1_50_B1': 750, 'P1_50_B2': 750, 'P1_50_B3': 750, 'P1_50_B4': 800, 'P1_30_B1': 750, 'P1_20_B4': 800, 'P1_40_B3': 750, 'P1_30_B4': 800, 'P1_X1_B0': 50, 'P1_10_B2': 750, 'P1_10_B3': 750, 'P2_C2_B2': 700, 'P2_C2_B4': 700, 'P2_C2_B3': 700, 'P1_X4_B0': 50, 'P1_50_B0': 750, 'P3_N1_B2': 700, 'P3_N2_B2': 700, 'P3_N3_B2': 700, 'P2_C3_B4': 750, 'P2_C3_B3': 750, 'P1_X2_B0': 50, 'P1_X3_B0': 50, 'P1_X5_B0': 50, 'P2_C2_B1': 750, 'P1_X2_B3': 50, 'P1_X2_B4': 50, 'P3_N5_B5': 700, 'P3_N6_B5': 700, 'P1_C1_B0': 600, 'P1_C2_B0': 600, 'P1_C3_B0': 600, 'P3_N4_B2': 700, 'P2_CN_B0': 600, 'P3_N7_B5': 700, 'P3_N8_B5': 700, 'P3_N9_B5': 700, 'P3_N10_B5': 700, 'P3_N11_B5': 700}

{'P1_30_B2': 750,
 'P1_40_B1': 750,
 'P2_C1_B0': 700,
 'P2_C2_B0': 700,
 'P2_C3_B0': 700,
 'P1_00_B1': 900,
 'P1_00_B2': 900,
 'P1_40_B2': 750,
 'P1_40_B4': 800,
 'P1_40_B0': 750,
 'P1_30_B3': 750,
 'P1_20_B0': 750,
 'P1_00_B3': 850,
 'P1_10_B0': 750,
 'P1_30_B0': 750,
 'P1_00_B4': 1000,
 'P1_20_B1': 750,
 'P1_10_B1': 750,
 'P1_00_B0': 750,
 'P1_10_B4': 850,
 'P1_20_B3': 750,
 'P1_20_B2': 750,
 'P1_50_B1': 750,
 'P1_50_B2': 750,
 'P1_50_B3': 750,
 'P1_50_B4': 800,
 'P1_30_B1': 750,
 'P1_20_B4': 800,
 'P1_40_B3': 750,
 'P1_30_B4': 800,
 'P1_X1_B0': 50,
 'P1_10_B2': 750,
 'P1_10_B3': 750,
 'P2_C2_B2': 700,
 'P2_C2_B4': 700,
 'P2_C2_B3': 700,
 'P1_X4_B0': 50,
 'P1_50_B0': 750,
 'P3_N1_B2': 700,
 'P3_N2_B2': 700,
 'P3_N3_B2': 700,
 'P2_C3_B4': 750,
 'P2_C3_B3': 750,
 'P1_X2_B0': 50,
 'P1_X3_B0': 50,
 'P1_X5_B0': 50,
 'P2_C2_B1': 750,
 'P1_X2_B3': 50,
 'P1_X2_B4': 50,
 'P3_N5_B5': 700,
 'P3_N6_B5': 700,
 'P1_C1_B0': 600,
 'P1_C2_B0': 600,
 'P1_C3_B0': 600,
 'P3_N4_B2': 700,
 'P2_CN_B0': 600,
 'P3_N7_B5': 700,
 'P3_N8_B5': 700,
 'P3_N9_B5': 700,
 'P3_N10_B5': 700,
 'P3_N11_B5': 700}

Now with the dictionary we create a new column for product prices.

In [45]:
#Assign the values from dictionary to a new column 

price_of_product = []

for version in anon_df["nozzle"]:
    price_of_product.append(price_dict[version])
    
price_of_product

anon_df.insert(6, "price_of_nozzle", price_of_product)

In [46]:
anon_df

,customer_id,product_family,size_new,coating_new,nozzle,amount,price_of_nozzle,date_order,date_delivery_is,delivery_time,machine_type,locality_country,locality_city,replacement_delivery
0,2,P1,30,B2,P1_30_B2,18.0,750,2018-11-30,2021-03-05,826.0,M0,UK,Witney,0.0
1,2,P1,30,B2,P1_30_B2,18.0,750,2018-11-30,2021-03-15,836.0,M0,UK,Witney,0.0
2,194,P1,40,B1,P1_40_B1,10.0,750,2019-03-19,2020-01-31,318.0,M4,South Korea,Seongnam-si (Gyeonggi-do),0.0
3,162,P2,C1,B0,P2_C1_B0,4.0,700,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0
4,162,P2,C2,B0,P2_C2_B0,4.0,700,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2782,2,P1,30,B2,P1_30_B2,35.0,750,2022-06-01,NaN,9999.0,none,Ireland,Donegal,0.0
2783,220,P1,30,B0,P1_30_B0,10.0,750,2022-07-13,NaN,9999.0,none,Ireland,Dungloe,0.0
2784,165,P1,30,B0,P1_30_B0,3.0,750,2021-09-02,NaN,9999.0,none,Germany,Potsdam-Golm,0.0
2785,95,P1,30,B2,P1_30_B2,3.0,750,2022-09-02,NaN,9999.0,M1,USA,Seattle,0.0
2786,237,P1,30,B1,P1_30_B1,2.0,750,2022-09-02,NaN,9999.0,M1,USA,Tempe,0.0

Lastly we create another column for our sales revenue to see how much actually per customer brought.

## Drop Nan Values to Clean

In [47]:
anon_df['date_delivery_is'].isna().sum()

159

In [48]:
anon_df=anon_df.dropna(subset=['date_delivery_is']) 
anon_df

,customer_id,product_family,size_new,coating_new,nozzle,amount,price_of_nozzle,date_order,date_delivery_is,delivery_time,machine_type,locality_country,locality_city,replacement_delivery
0,2,P1,30,B2,P1_30_B2,18.0,750,2018-11-30,2021-03-05,826.0,M0,UK,Witney,0.0
1,2,P1,30,B2,P1_30_B2,18.0,750,2018-11-30,2021-03-15,836.0,M0,UK,Witney,0.0
2,194,P1,40,B1,P1_40_B1,10.0,750,2019-03-19,2020-01-31,318.0,M4,South Korea,Seongnam-si (Gyeonggi-do),0.0
3,162,P2,C1,B0,P2_C1_B0,4.0,700,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0
4,162,P2,C2,B0,P2_C2_B0,4.0,700,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,182,P1,30,B4,P1_30_B4,1.0,800,2022-08-01,2022-08-22,21.0,none,Finnland,Espoo,1.0
2760,242,P1,30,B3,P1_30_B3,1.0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0
2761,242,P1,30,B3,P1_30_B3,1.0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0
2762,242,P1,30,B3,P1_30_B3,1.0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0
2763,242,P1,30,B3,P1_30_B3,1.0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0

In [49]:
anon_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2627 entries, 0 to 2763
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           2627 non-null   int64
 1   product_family        2627 non-null   object
 2   size_new              2627 non-null   object
 3   coating_new           2627 non-null   object
 4   nozzle                2627 non-null   object
 5   amount                2627 non-null   float64
 6   price_of_nozzle       2627 non-null   int64
 7   date_order            2627 non-null   object
 8   date_delivery_is      2627 non-null   object
 9   delivery_time         2627 non-null   float64
 10  machine_type          2627 non-null   object
 11  locality_country      2627 non-null   object
 12  locality_city         2625 non-null   object
 13  replacement_delivery  2627 non-null   float64
dtypes: float64(3), int64(2), object(9)
memory usage: 307.9+ KB

## Adding Machine Prices

In [50]:
customer_df = pd.read_csv("/Users/esrabecker/Desktop/GitHub/DA_Midterm_Project/Customer_Notebook/anonymised_customer.csv", sep= ';')
pd.set_option('display.max_columns', None)
customer_df

,Unnamed: 0,customer_id,product_family,size_new,coating_new,nozzle,price_of_nozzle,amount,machine_type,price_of_machine,date_order,date_delivery_is,delivery_time,locality_country,locality_city,replacement_delivery,sales_revenue
0,0,2,P1,30,B2,P1_30_B2,750,18.0,M0,25000,2018-11-30,2021-03-05,826.0,UK,Witney,0.0,38500.0
1,1,2,P1,30,B2,P1_30_B2,750,18.0,M0,25000,2018-11-30,2021-03-15,836.0,UK,Witney,0.0,38500.0
2,2,194,P1,40,B1,P1_40_B1,750,10.0,M4,1000000,2019-03-19,2020-01-31,318.0,South Korea,Seongnam-si (Gyeonggi-do),0.0,1007500.0
3,3,162,P2,C1,B0,P2_C1_B0,700,4.0,none,0,2019-04-26,2020-02-26,306.0,Germany,Berlin,0.0,2800.0
4,4,162,P2,C2,B0,P2_C2_B0,700,4.0,none,0,2019-04-26,2020-02-26,306.0,Germany,Berlin,0.0,2800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,2759,182,P1,30,B4,P1_30_B4,800,1.0,none,0,2022-08-01,2022-08-22,21.0,Finnland,Espoo,1.0,800.0
2623,2760,242,P1,30,B3,P1_30_B3,750,1.0,none,0,2022-08-04,2022-08-08,4.0,USA,Mishawaka,1.0,750.0
2624,2761,242,P1,30,B3,P1_30_B3,750,1.0,none,0,2022-08-04,2022-08-08,4.0,USA,Mishawaka,1.0,750.0
2625,2762,242,P1,30,B3,P1_30_B3,750,1.0,none,0,2022-08-04,2022-08-08,4.0,USA,Mishawaka,1.0,750.0
2626,2763,242,P1,30,B3,P1_30_B3,750,1.0,none,0,2022-08-04,2022-08-08,4.0,USA,Mishawaka,1.0,750.0

In [51]:
#keys of the machine list
machine_keys = list(anon_df['machine_type'].unique())
machine_keys

['M0',
 'M4',
 'none',
 'M7',
 'M3',
 'M2',
 'M1',
 'M5',
 'M6',
 'not a machine',
 'M8',
 'M7B',
 'M3N',
 'M9',
 'M1N']

In [52]:
prices_values =  list([25000, 1000000, 0, 55000, 100000, 35000, 40000, 55000, 55000, 0, 60000, 55000, 120000, 75000, 50000])
prices_values

[25000,
 1000000,
 0,
 55000,
 100000,
 35000,
 40000,
 55000,
 55000,
 0,
 60000,
 55000,
 120000,
 75000,
 50000]

In [53]:
# create dictionary for the prices of each product
def price_dict(machine_keys, prices_values):
    result = {} # empty dictionary
    for key, value in zip(machine_keys, prices_values):
        result[key] = value
    return result

print(price_dict(machine_keys=machine_keys, prices_values=prices_values))

price_dict= price_dict(machine_keys=machine_keys, prices_values=prices_values)
price_dict

{'M0': 25000, 'M4': 1000000, 'none': 0, 'M7': 55000, 'M3': 100000, 'M2': 35000, 'M1': 40000, 'M5': 55000, 'M6': 55000, 'not a machine': 0, 'M8': 60000, 'M7B': 55000, 'M3N': 120000, 'M9': 75000, 'M1N': 50000}

{'M0': 25000,
 'M4': 1000000,
 'none': 0,
 'M7': 55000,
 'M3': 100000,
 'M2': 35000,
 'M1': 40000,
 'M5': 55000,
 'M6': 55000,
 'not a machine': 0,
 'M8': 60000,
 'M7B': 55000,
 'M3N': 120000,
 'M9': 75000,
 'M1N': 50000}

In [54]:
#Assign the values from dictionary to a new column 

price_of_machine = []

for machine in anon_df["machine_type"]:
    price_of_machine.append(price_dict[machine])
    
price_of_machine

anon_df.insert(6, "price_of_machine", price_of_machine)

In [55]:
anon_df

,customer_id,product_family,size_new,coating_new,nozzle,amount,price_of_machine,price_of_nozzle,date_order,date_delivery_is,delivery_time,machine_type,locality_country,locality_city,replacement_delivery
0,2,P1,30,B2,P1_30_B2,18.0,25000,750,2018-11-30,2021-03-05,826.0,M0,UK,Witney,0.0
1,2,P1,30,B2,P1_30_B2,18.0,25000,750,2018-11-30,2021-03-15,836.0,M0,UK,Witney,0.0
2,194,P1,40,B1,P1_40_B1,10.0,1000000,750,2019-03-19,2020-01-31,318.0,M4,South Korea,Seongnam-si (Gyeonggi-do),0.0
3,162,P2,C1,B0,P2_C1_B0,4.0,0,700,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0
4,162,P2,C2,B0,P2_C2_B0,4.0,0,700,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,182,P1,30,B4,P1_30_B4,1.0,0,800,2022-08-01,2022-08-22,21.0,none,Finnland,Espoo,1.0
2760,242,P1,30,B3,P1_30_B3,1.0,0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0
2761,242,P1,30,B3,P1_30_B3,1.0,0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0
2762,242,P1,30,B3,P1_30_B3,1.0,0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0
2763,242,P1,30,B3,P1_30_B3,1.0,0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0

In [56]:
anon_df['sales_revenue'] = anon_df.price_of_nozzle * anon_df.amount + anon_df.price_of_machine
anon_df

/var/folders/c3/pkgzz_891b148813l5gzlgl40000gn/T/ipykernel_68606/299574177.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anon_df['sales_revenue'] = anon_df.price_of_nozzle * anon_df.amount + anon_df.price_of_machine

,customer_id,product_family,size_new,coating_new,nozzle,amount,price_of_machine,price_of_nozzle,date_order,date_delivery_is,delivery_time,machine_type,locality_country,locality_city,replacement_delivery,sales_revenue
0,2,P1,30,B2,P1_30_B2,18.0,25000,750,2018-11-30,2021-03-05,826.0,M0,UK,Witney,0.0,38500.0
1,2,P1,30,B2,P1_30_B2,18.0,25000,750,2018-11-30,2021-03-15,836.0,M0,UK,Witney,0.0,38500.0
2,194,P1,40,B1,P1_40_B1,10.0,1000000,750,2019-03-19,2020-01-31,318.0,M4,South Korea,Seongnam-si (Gyeonggi-do),0.0,1007500.0
3,162,P2,C1,B0,P2_C1_B0,4.0,0,700,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0,2800.0
4,162,P2,C2,B0,P2_C2_B0,4.0,0,700,2019-04-26,2020-02-26,306.0,none,Germany,Berlin,0.0,2800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,182,P1,30,B4,P1_30_B4,1.0,0,800,2022-08-01,2022-08-22,21.0,none,Finnland,Espoo,1.0,800.0
2760,242,P1,30,B3,P1_30_B3,1.0,0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0,750.0
2761,242,P1,30,B3,P1_30_B3,1.0,0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0,750.0
2762,242,P1,30,B3,P1_30_B3,1.0,0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0,750.0
2763,242,P1,30,B3,P1_30_B3,1.0,0,750,2022-08-04,2022-08-08,4.0,none,USA,Mishawaka,1.0,750.0

In [57]:
anon_df = anon_df[[
    "customer_id", "product_family", "size_new", "coating_new", "nozzle", "price_of_nozzle", "amount","machine_type", "price_of_machine", "date_order", "date_delivery_is", "delivery_time",
    "locality_country", "locality_city", "replacement_delivery", "sales_revenue"]]
anon_df

,customer_id,product_family,size_new,coating_new,nozzle,price_of_nozzle,amount,machine_type,price_of_machine,date_order,date_delivery_is,delivery_time,locality_country,locality_city,replacement_delivery,sales_revenue
0,2,P1,30,B2,P1_30_B2,750,18.0,M0,25000,2018-11-30,2021-03-05,826.0,UK,Witney,0.0,38500.0
1,2,P1,30,B2,P1_30_B2,750,18.0,M0,25000,2018-11-30,2021-03-15,836.0,UK,Witney,0.0,38500.0
2,194,P1,40,B1,P1_40_B1,750,10.0,M4,1000000,2019-03-19,2020-01-31,318.0,South Korea,Seongnam-si (Gyeonggi-do),0.0,1007500.0
3,162,P2,C1,B0,P2_C1_B0,700,4.0,none,0,2019-04-26,2020-02-26,306.0,Germany,Berlin,0.0,2800.0
4,162,P2,C2,B0,P2_C2_B0,700,4.0,none,0,2019-04-26,2020-02-26,306.0,Germany,Berlin,0.0,2800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,182,P1,30,B4,P1_30_B4,800,1.0,none,0,2022-08-01,2022-08-22,21.0,Finnland,Espoo,1.0,800.0
2760,242,P1,30,B3,P1_30_B3,750,1.0,none,0,2022-08-04,2022-08-08,4.0,USA,Mishawaka,1.0,750.0
2761,242,P1,30,B3,P1_30_B3,750,1.0,none,0,2022-08-04,2022-08-08,4.0,USA,Mishawaka,1.0,750.0
2762,242,P1,30,B3,P1_30_B3,750,1.0,none,0,2022-08-04,2022-08-08,4.0,USA,Mishawaka,1.0,750.0
2763,242,P1,30,B3,P1_30_B3,750,1.0,none,0,2022-08-04,2022-08-08,4.0,USA,Mishawaka,1.0,750.0

In [58]:
anon_df.to_csv('anonymised_customer.csv', sep=';')